<!doctype html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>İZGİOS | Kurumsal Giriş</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        *{box-sizing:border-box}body{margin:0;background:#edf3fb;color:#17233c;font-family:Poppins,system-ui}.portal{min-height:100vh;display:grid;grid-template-columns:1.12fr .88fr}.brand-panel{padding:clamp(42px,8vw,104px);background:radial-gradient(circle at top right,#3469dc 0,#1d4ed8 28%,#101b33 76%);color:#fff;display:flex;align-items:center}.brand{font-size:40px;font-weight:800;letter-spacing:-2px}.brand b{color:#e8bd38}.eyebrow{margin-top:10px;color:#cfe0ff;font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.brand-panel h1{max-width:570px;margin:38px 0 18px;font-size:clamp(32px,4vw,49px);line-height:1.13}.brand-panel p{max-width:570px;color:#dce8ff;line-height:1.75;font-size:15px}.proof{display:flex;gap:11px;flex-wrap:wrap;margin-top:27px}.proof span{padding:8px 10px;border:1px solid rgba(255,255,255,.22);border-radius:999px;background:rgba(255,255,255,.08);font-size:12px}.demo-link{display:inline-flex;margin-top:26px;padding:13px 17px;border-radius:10px;background:#fff;color:#1d4ed8;text-decoration:none;font-size:13px;font-weight:800}.login-panel{padding:34px;display:flex;align-items:center;justify-content:center}.login-card{width:min(100%,425px);padding:34px;background:#fff;border:1px solid #dae4f0;border-radius:21px;box-shadow:0 18px 48px rgba(15,23,42,.12)}.login-card h2{margin:0;font-size:26px}.lead{margin:8px 0 24px;color:#64748b;font-size:14px}.notice{margin-bottom:15px;padding:11px;border-radius:9px;background:#fee2e2;color:#991b1b;font-size:13px}.field{margin-bottom:17px}.field label{display:block;margin-bottom:7px;font-size:13px;font-weight:700}.field input{width:100%;padding:12px;border:1px solid #cdd8e6;border-radius:10px;font:14px Poppins;outline:none}.field input:focus{border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.12)}.remember{display:flex;align-items:center;gap:8px;margin-bottom:20px;color:#64748b;font-size:12px}.login-card button{width:100%;border:0;border-radius:10px;padding:13px;background:#2563eb;color:#fff;font:800 14px Poppins;cursor:pointer}.contact{margin-top:24px;padding-top:18px;border-top:1px solid #e7edf4;text-align:center;color:#64748b;font-size:12px;line-height:1.9}.contact a{color:#1d4ed8;text-decoration:none;font-weight:700}@media(max-width:800px){.portal{grid-template-columns:1fr}.brand-panel{padding:48px 30px}.login-panel{padding:30px 18px}}
    </style>
</head>
<body>
<main class="portal">
    <section class="brand-panel"><div><div class="brand">İZGİ<b>OS</b></div><div class="eyebrow">Online oto servis otomasyonu</div><h1>Her firma kendi markasıyla, tek güçlü altyapıda.</h1><p>İZGİOS; servis kabul, iş emri, müşteri, araç, stok, mali işlemler ve raporları rolünüze göre tek çalışma alanında birleştirir.</p><div class="proof"><span>Çoklu firma</span><span>Çoklu şube</span><span>Rol bazlı yetki</span><span>Online erişim</span></div><a class="demo-link" href="{{ route('demo') }}">Programı Keşfet →</a></div></section>
    <section class="login-panel"><div class="login-card"><h2>Çalışma alanınıza giriş yapın</h2><p class="lead">Hesabınız bağlı olduğu firma ve şubeye göre açılır.</p>
        @if(session('error'))<div class="notice">{{ session('error') }}</div>@endif
        @if($errors->any())<div class="notice">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('login.post') }}">@csrf<div class="field"><label for="login">E-posta</label><input id="login" type="email" name="login" value="{{ old('login') }}" placeholder="ornek@firma.com" required autofocus></div><div class="field"><label for="password">Şifre</label><div style="position:relative"><input id="password" type="password" name="password" placeholder="Şifreniz" required style="padding-right:52px"><button id="password-toggle" type="button" aria-label="Şifreyi göster" style="position:absolute;right:6px;top:6px;width:38px;padding:6px;border:0;background:transparent;color:#2563eb;font-size:18px"><span id="password-icon">👁</span></button></div></div><label class="remember"><input type="checkbox" name="remember"> Beni hatırla</label><button type="submit">Güvenli Giriş Yap</button></form><p style="margin:14px 0 0;text-align:center;font-size:12px"><a style="color:#1d4ed8;font-weight:700;text-decoration:none" href="{{ route('password.request') }}">Şifremi unuttum</a></p><div class="contact">İZGİOS satış ve destek<br><a href="tel:+905374916936">0537 491 69 36</a> · <a href="https://wa.me/905374916936" target="_blank" rel="noopener">WhatsApp</a> · <a href="mailto:info@izgios.com">info@izgios.com</a></div></div></section>
</main>
<script>document.getElementById('password-toggle').addEventListener('click',function(){const p=document.getElementById('password');const show=p.type==='password';p.type=show?'text':'password';this.setAttribute('aria-label',show?'Şifreyi gizle':'Şifreyi göster');document.getElementById('password-icon').textContent=show?'🙈':'👁';});</script></body></html>
