<div class="genel-ai" id="genel-ai">
    <button class="genel-ai__trigger" type="button" aria-expanded="false" aria-controls="genel-ai-panel"><i class="bi bi-stars"></i><span>Yapay Zekâ Asistanı</span></button>
    <section class="genel-ai__panel" id="genel-ai-panel" hidden>
        <header><div><strong><i class="bi bi-cpu-fill"></i> İZGİOS Asistanı</strong><small>Yol gösterir, işlem yapmaz.</small></div><button type="button" class="genel-ai__close" aria-label="Kapat"><i class="bi bi-x-lg"></i></button></header>
        <div class="genel-ai__messages"><div class="genel-ai__message">Merhaba. Müşteri, araç, servis kabul, iş emri, depo, muhasebe, raporlar ve ayarlar hakkında yardımcı olabilirim. Teknik hata için ekran adresi ve hata kodunu yazın.</div></div>
        <div class="genel-ai__quick"><button type="button" data-question="Yeni servis kabulü nasıl açılır?">Servis kabul</button><button type="button" data-question="Müşteriye araç nasıl eklenir?">Müşteri ve araç</button><button type="button" data-question="İş emrini nasıl üzerime alırım?">İş emri</button><a href="{{ route('sss.index') }}">Sık sorulan sorular</a></div>
        <form class="genel-ai__form"><input name="mesaj" maxlength="2000" autocomplete="off" placeholder="Sorunuzu yazın…" required><button type="submit" aria-label="Gönder"><i class="bi bi-send-fill"></i></button></form>
        <p>İletişim bilgileri maskelenerek analiz edilir. Kritik işlem veya hata için Destek Merkezi’ne yönlendirilirsiniz.</p>
    </section>
</div>
<script>
(() => { const root=document.getElementById('genel-ai'); if(!root)return; const trigger=root.querySelector('.genel-ai__trigger'), panel=root.querySelector('.genel-ai__panel'), close=root.querySelector('.genel-ai__close'), messages=root.querySelector('.genel-ai__messages'), form=root.querySelector('form'), input=form.querySelector('input'); const toggle=(open)=>{panel.hidden=!open;trigger.setAttribute('aria-expanded',String(open));if(open)input.focus()}; trigger.onclick=()=>toggle(panel.hidden);close.onclick=()=>toggle(false); const ask=async(message)=>{if(!message.trim())return;messages.insertAdjacentHTML('beforeend',`<div class="genel-ai__message genel-ai__message--user"></div>`);messages.lastElementChild.textContent=message;input.value=''; const wait=document.createElement('div');wait.className='genel-ai__message';wait.textContent='Yanıt hazırlanıyor…';messages.append(wait);messages.scrollTop=messages.scrollHeight;try{const res=await fetch('{{ route('asistan.yanitla') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({mesaj:message})});const data=await res.json();wait.textContent=data.yanit||'Yanıt alınamadı. Destek Merkezi üzerinden talep oluşturun.'}catch(e){wait.textContent='Bağlantı kurulamadı. Lütfen Destek Merkezi üzerinden talep oluşturun.'}messages.scrollTop=messages.scrollHeight}; form.onsubmit=e=>{e.preventDefault();ask(input.value)};root.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>ask(b.dataset.question));})();
</script>
