<style>
    .izgi-card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:22px}
    .izgi-card{display:flex;flex-direction:column;min-width:0;background:#fff;border:1px solid #dce5f1;border-radius:22px;overflow:hidden;box-shadow:0 12px 30px rgba(15,35,69,.08);color:#102b52}
    .izgi-card__head{display:flex;align-items:flex-start;gap:12px;padding:21px 22px 17px;border-bottom:1px solid #e4ebf4;background:linear-gradient(135deg,#fffdf4 0%,#fff 70%)}
    .izgi-card__icon{flex:0 0 42px;width:42px;height:42px;display:grid;place-items:center;border-radius:14px;background:#edf3ff;color:#1d5cff;font-size:21px}
    .izgi-card__title-wrap{min-width:0;flex:1}.izgi-card__eyebrow{margin:0 0 4px;font-size:12px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;color:#7284a0}.izgi-card__title{margin:0;font-size:20px;line-height:1.25;font-weight:850;color:#102b52;overflow-wrap:anywhere}.izgi-card__subtitle{margin:5px 0 0;color:#657896;font-size:14px;font-weight:650}
    .izgi-card__body{padding:18px 22px 20px;flex:1}.izgi-card__meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.izgi-card__meta--single{grid-template-columns:1fr}.izgi-card__meta-item{min-width:0;padding:12px 13px;border-radius:13px;background:#f7f9fc}.izgi-card__label{display:block;margin-bottom:5px;font-size:12px;font-weight:750;color:#7485a0}.izgi-card__value{display:block;font-size:15px;line-height:1.35;font-weight:800;color:#102b52;overflow-wrap:anywhere}.izgi-card__status{display:inline-flex;align-items:center;gap:6px;width:max-content;padding:6px 10px;border-radius:999px;background:#eaf8ef;color:#16743b;font-size:12px;font-weight:850}.izgi-card__status--passive{background:#fff0ef;color:#bf3d33}
    .izgi-card__footer{display:grid;grid-template-columns:repeat(var(--izgi-card-actions,2),minmax(0,1fr));gap:9px;padding:14px 16px 16px;border-top:1px solid #e4ebf4;background:#fbfcfe}.izgi-card__action{min-width:0;min-height:43px;padding:8px 10px;border:1px solid transparent;border-radius:12px;display:flex;align-items:center;justify-content:center;gap:6px;text-align:center;text-decoration:none;font-size:13px;font-weight:850;line-height:1.15;cursor:pointer;transition:.18s ease;background:#fff}.izgi-card__action:hover{transform:translateY(-1px);filter:brightness(.98)}.izgi-card__action--primary{background:#e3b82e;color:#fff;border-color:#e3b82e}.izgi-card__action--outline{background:#fff;color:#1d5cff;border-color:#bfd2ff}.izgi-card__action--soft{background:#eef4ff;color:#2456bd}.izgi-card__action--danger{background:#fff0ef;color:#c23d35;border-color:#ffd8d4}.izgi-card__footer form{margin:0;min-width:0}.izgi-card__footer form .izgi-card__action{width:100%}
    body.dark-theme .izgi-card{background:#16243b;border-color:#344967;color:#edf4ff;box-shadow:none}body.dark-theme .izgi-card__head{background:linear-gradient(135deg,#1b2b45,#16243b);border-color:#344967}body.dark-theme .izgi-card__title,body.dark-theme .izgi-card__value{color:#f6f9ff}body.dark-theme .izgi-card__subtitle,body.dark-theme .izgi-card__label,body.dark-theme .izgi-card__eyebrow{color:#b8c7dc}body.dark-theme .izgi-card__meta-item,body.dark-theme .izgi-card__footer{background:#122038;border-color:#344967}body.dark-theme .izgi-card__action--outline{background:#172b4a;color:#9bbcff;border-color:#416aa7}body.dark-theme .izgi-card__action--soft{background:#1b345b;color:#bfd4ff}
    @media(max-width:640px){.izgi-card-grid{grid-template-columns:1fr;gap:15px}.izgi-card__head{padding:17px}.izgi-card__body{padding:15px 17px}.izgi-card__footer{padding:12px;gap:8px}.izgi-card__title{font-size:18px}.izgi-card__meta{gap:9px}.izgi-card__meta-item{padding:10px}.izgi-card__action{font-size:12px;min-height:42px}}
</style>
