@extends('layouts.app')
@section('title','Servis Tamir Ekranı | İZGİOS')
@section('content')
<section class="container py-4 servis-form servis-islem-v4"><div class="servis-form-hero"><div><div class="eyebrow">SERVİS AKIŞI · 4. ADIM</div><h1>{{ $servis->servis_no }}</h1><p>{{ $servis->arac?->plaka }} · {{ $servis->arac?->marka }} {{ $servis->arac?->model }} · {{ number_format($servis->giris_km ?? 0,0,',','.') }} KM</p></div><span class="islem-durum">{{ $servis->durum }}</span></div>
@include('components.servis-akisi', ['aktifAdim' => 4])
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
@if($ustaUzerineAlabilir ?? false)<article class="card corporate-form"><div class="card-body p-4 p-lg-5 text-center"><i class="bi bi-person-check-fill fs-1 text-primary"></i><h2 class="h4 mt-3">İş Emrini Üzerinize Alın</h2><p class="text-muted">Üzerinize aldığınız iş emri yalnızca sizin usta çalışma listenizde görünür.</p><form method="POST" action="{{ route('servis.uzerine.al',$servis) }}">@csrf<button class="btn btn-primary px-4">İş Emrini Üzerime Al</button></form></div></article>
@else
<div class="row g-4"><div class="col-lg-7"><article class="card corporate-form mb-4"><div class="card-body p-4"><div class="form-section-title"><i class="bi bi-clipboard-data"></i><div><h2>Kabul özeti ve servis durumu</h2><p>{{ $servis->musteri?->ad_soyad }} · {{ optional($servis->servis_tarihi)->format('d.m.Y H:i') }}</p></div></div><div class="kabul-ozet"><div><span>Şikayet</span><strong>{{ $servis->sikayet ?: '-' }}</strong></div><div><span>İlk kontrol</span><strong>{{ $servis->usta_notu ?: '-' }}</strong></div></div><form method="POST" action="{{ route('servis.islem.durum',$servis) }}" class="row g-3 mt-1">@csrf<div class="col-md-5"><label>Servis durumu</label><select name="durum"><option @selected($servis->durum==='Bekliyor')>Bekliyor</option><option @selected($servis->durum==='İşlemde')>İşlemde</option><option @selected($servis->durum==='Teslime Hazır')>Teslime Hazır</option><option @selected($servis->durum==='Tamamlandı')>Tamamlandı</option></select></div><div class="col-md-7"><label>Usta notu</label><input name="usta_notu" value="{{ $servis->usta_notu }}" placeholder="Güncel servis notu"></div><div class="col-12"><button class="btn btn-outline-primary">Durumu Kaydet</button></div></form></div></article>
<article class="card corporate-form"><div class="card-body p-4"><div class="form-section-title"><i class="bi bi-tools"></i><div><h2>Yapılan işlemler</h2><p>İşçilik ve uygulanan işlemleri kaydedin.</p></div></div>@forelse($servis->islemler as $islem)<div class="kayit-satir"><i class="bi bi-check-circle-fill"></i><div><strong>{{ $islem->islem_adi }}</strong><small>{{ $islem->aciklama }}</small></div><b>₺{{ number_format($islem->tutar,2,',','.') }}</b></div>@empty<div class="bos-not">Henüz işlem eklenmedi.</div>@endforelse<form method="POST" action="{{ route('servis.islem.ekle',$servis) }}" class="row g-2 mt-3">@csrf<div class="col-md-5"><input name="islem_adi" required placeholder="Yapılan işlem"></div><div class="col-md-4"><input name="aciklama" placeholder="Kısa açıklama"></div><div class="col-md-3"><input type="number" step=".01" name="tutar" placeholder="İşçilik tutarı"></div><div class="col-12"><button class="btn btn-primary">İşlem Ekle</button></div></form></div></article></div>
<div class="col-lg-5"><article class="card corporate-form mb-4"><div class="card-body p-4"><div class="form-section-title"><i class="bi bi-box-seam"></i><div><h2>Kullanılan parçalar</h2><p>Değişen parçaları maliyetiyle ekleyin.</p></div></div>@forelse($servis->parcalar as $parca)<div class="kayit-satir"><i class="bi bi-gear-fill"></i><div><strong>{{ $parca->parca_adi }}</strong><small>{{ $parca->adet }} adet</small></div><b>₺{{ number_format($parca->toplam_fiyat,2,',','.') }}</b></div>@empty<div class="bos-not">Henüz parça eklenmedi.</div>@endforelse<form method="POST" action="{{ route('servis.parca.ekle',$servis) }}" class="row g-2 mt-3">@csrf<div class="col-12"><input name="parca_adi" required placeholder="Parça adı"></div><div class="col-6"><input type="number" name="adet" value="1" min="1" required></div><div class="col-6"><input type="number" step=".01" name="birim_fiyat" placeholder="Birim fiyat"></div><div class="col-12"><button class="btn btn-outline-primary">Parçayı Ekle</button></div></form></div></article>
<article class="card corporate-form mb-4"><div class="card-body p-4"><div class="form-section-title"><i class="bi bi-camera"></i><div><h2>Servis fotoğrafları</h2><p>Kamera doğrudan açılır.</p></div></div><div class="foto-liste">@foreach($servis->fotograflar as $foto)<img src="{{ asset('storage/'.$foto->dosya_yolu) }}" alt="Servis fotoğrafı">@endforeach</div><form method="POST" enctype="multipart/form-data" action="{{ route('servis.fotograf.ekle',$servis) }}" class="row g-2 mt-3">@csrf<div class="col-md-6"><select name="kategori"><option value="islem">Servis işlemi</option><option value="parca">Değişen parça</option><option value="teslim">Teslim</option></select></div><div class="col-md-6"><input type="file" name="foto" accept="image/*" capture="environment" required></div><div class="col-12"><input name="aciklama" placeholder="Fotoğraf açıklaması"></div><div class="col-12"><button class="btn btn-outline-primary"><i class="bi bi-camera-fill"></i> Kamera ile Fotoğraf Ekle</button></div></form></div></article>
<article class="card corporate-form"><div class="card-body p-4"><div class="form-section-title"><i class="bi bi-calculator"></i><div><h2>Maliyet özeti</h2></div></div><div class="maliyet-satir"><span>İşçilik</span><b>₺{{ number_format($servis->iscilik_tutari,2,',','.') }}</b></div><div class="maliyet-satir"><span>Yedek parça</span><b>₺{{ number_format($servis->parca_tutari,2,',','.') }}</b></div><div class="maliyet-satir genel"><span>Genel toplam</span><b>₺{{ number_format($servis->toplam_tutar,2,',','.') }}</b></div></div></article></div></div>@endif</section>
@include('components.servis-form-style')
<style>.islem-durum{padding:.55rem .85rem;border:1px solid rgba(255,255,255,.4);border-radius:999px;font-weight:800}.kabul-ozet{display:grid;gap:.75rem;padding:1rem;border-radius:12px;background:#f6faff}.kabul-ozet div{display:flex;flex-direction:column;gap:.25rem}.kabul-ozet span{font-size:.74rem;font-weight:750;color:#70839e}.kabul-ozet strong{font-size:.9rem;color:#263d5e}.kayit-satir{display:flex;align-items:flex-start;gap:.65rem;padding:.8rem 0;border-bottom:1px solid #e6edf5}.kayit-satir>i{color:#11806c;margin-top:.15rem}.kayit-satir div{flex:1}.kayit-satir strong,.kayit-satir small{display:block}.kayit-satir small{color:#71839e;font-size:.8rem}.kayit-satir b{font-size:.85rem;color:#142b4e}.bos-not{padding:.8rem;border-radius:10px;background:#f6faff;color:#71839e;font-size:.88rem}.foto-liste{display:flex;gap:.5rem;flex-wrap:wrap}.foto-liste img{width:92px;height:70px;object-fit:cover;border-radius:9px}.maliyet-satir{display:flex;justify-content:space-between;padding:.7rem 0;border-bottom:1px solid #e6edf5;color:#667a96}.maliyet-satir b{color:#142b4e}.maliyet-satir.genel{font-size:1.05rem;border:0;color:#142b4e}.maliyet-satir.genel b{color:#087a70}.tema-koyu .kabul-ozet,.tema-koyu .bos-not{background:#202f49}.tema-koyu .kabul-ozet strong,.tema-koyu .kayit-satir b,.tema-koyu .maliyet-satir b{color:#edf4ff}.tema-koyu .kayit-satir,.tema-koyu .maliyet-satir{border-color:#31415b}</style>
@endsection
