@extends('layouts.app')
@section('title','Servis Kabul | İZGİOS')
@section('content')
<style>
    .kabul-teslim-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }
    .kabul-kamera-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; }
    .kabul-kamera-girdi { display: none !important; }
    .kabul-kamera-btn { display: flex; min-height: 88px; flex-direction: column; align-items: center; justify-content: center; gap: 6px; border: 1px solid #d2deed; border-radius: 12px; background: #f8fbff; color: #163d6c; font-weight: 800; }
    .kabul-kamera-btn:hover { border-color: #dfb536; background: #fff9e7; color: #142b4e; }
    .kabul-kamera-btn i { color: #c89d18; font-size: 1.45rem; }
    .kabul-kamera-durum { color: #6b7f99; font-size: .74rem; font-weight: 600; }
    .servis-aksiyonlar { display: flex; justify-content: center; align-items: center; gap: 14px; flex-wrap: wrap; }
    .kabul-tarama-btn { min-height: 44px; padding: 0 14px; border: 1px solid #e3b82e; border-radius: 11px; background: #e3b82e; color: #fff; font-weight: 850; }
    .kabul-tarama-btn--plaka { background: #fff; color: #163d6c; border-color: #cbd9ea; }
    @media (max-width: 900px) { .kabul-teslim-grid { grid-template-columns: 1fr; } }
    @media (max-width: 700px) { .kabul-kamera-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }
</style>
<main class="container py-4"><x-servis-yeni-tasarim :adim="3" baslik="Servis kabul" aciklama="Araç teslimini hızlıca kaydedin; iş emri bir sonraki ekranda başlar." />
@if($errors->any())<div class="alert alert-danger">Araç, müşteri ve şikayet alanlarını kontrol edin.</div>@endif
<form method="POST" action="{{ route('servis.kabul.store') }}" enctype="multipart/form-data" class="servis-sayfa-kart" id="kabulForm">@csrf
<div class="kart-baslik"><h2>1. Araç seçimi</h2><p>Plaka arayın, listeden seçin veya tablet/telefonda QR okutun.</p></div>
<div class="servis-form-grid"><div class="tam"><label>Plaka ile ara</label><div class="input-group"><input id="plakaAra" class="form-control text-uppercase" placeholder="Örn: 34 ABC 123"><button class="kabul-tarama-btn" type="button" id="qrButon"><i class="bi bi-qr-code-scan"></i> QR oku</button><button class="kabul-tarama-btn kabul-tarama-btn--plaka" type="button" id="plakaKamera"><i class="bi bi-camera"></i> Plaka kamera</button></div><div class="servis-bilgi-notu mt-2">QR veya plaka fotoğrafı okunduğunda eşleşen araç otomatik seçilir.</div><div class="servis-bilgi-notu mt-1" id="taramaDurum" role="status" aria-live="polite"></div></div><div class="tam"><label>Kayıtlı araç <span class="text-danger">*</span></label><select class="form-select" name="arac_id" id="aracId" required><option value="">Araç seçin</option>@foreach($araclar as $arac)<option value="{{ $arac->id }}" data-musteri="{{ $arac->musteri_id }}" data-plaka="{{ $arac->plaka }}" @selected(old('arac_id',$seciliAracId)==$arac->id)>{{ $arac->plaka }} · {{ $arac->marka }} {{ $arac->model }} · {{ $arac->musteri?->ad_soyad }}</option>@endforeach</select><input type="hidden" name="musteri_id" id="musteriId" value="{{ old('musteri_id') }}"></div><div><label>Giriş kilometresi</label><input class="form-control" type="number" name="giris_km" min="0" inputmode="numeric" value="{{ old('giris_km') }}" placeholder="KM"></div><div><label>Öncelik</label><select class="form-select" name="oncelik"><option value="Normal">Normal</option><option value="Acil">Acil</option><option value="Bekleyen">Parça / onay bekliyor</option></select></div><div class="tam"><label>Müşteri şikayeti / talebi <span class="text-danger">*</span></label><textarea class="form-control" name="sikayet" required placeholder="Müşterinin talebini kısa ve anlaşılır biçimde yazın">{{ old('sikayet') }}</textarea></div></div>
<div class="kart-baslik"><h2>2. Teslim bilgileri</h2><p>Bu bilgiler sadece teslim anını belgelemek için kaydedilir.</p></div><div class="servis-form-grid kabul-teslim-grid"><div><label>Yakıt seviyesi</label><select class="form-select" name="yakit_seviyesi"><option value="">Belirtilmedi</option><option>Boş</option><option>1/4</option><option>1/2</option><option>3/4</option><option>Dolu</option></select></div><div><label>Anahtar durumu</label><select class="form-select" name="anahtar_durumu"><option value="">Seçin</option><option value="ARAÇTA">Araçta</option><option value="YOK">Yok</option></select></div><div><label>Ruhsat araçta mı?</label><select class="form-select" name="ruhsat_aracta"><option value="">Seçin</option><option value="1">Evet</option><option value="0">Hayır</option></select></div><div class="tam"><label>İlk kabul notu</label><textarea class="form-control" name="arac_durum_notu" placeholder="Gözle görülen durum veya teslim notu"></textarea></div><div class="tam"><label>Araç dış fotoğrafları</label><p class="servis-bilgi-notu mb-2">Yönü seçin; tablet veya telefonda doğrudan arka kamera açılır. Çekimden sonra fotoğraf bu servis kabul kaydına eklenir.</p><div class="kabul-kamera-grid">@foreach(['on'=>'Ön','sag'=>'Sağ','sol'=>'Sol','arka'=>'Arka'] as $key=>$label)<div><input id="kamera-{{ $key }}" class="kabul-kamera-girdi" type="file" name="fotograflar[{{ $key }}]" accept="image/*" capture="environment" hidden><button type="button" class="kabul-kamera-btn w-100" data-kamera-hedef="kamera-{{ $key }}"><i class="bi bi-camera-fill"></i><span>{{ $label }} fotoğraf çek</span><small class="kabul-kamera-durum" id="kamera-durum-{{ $key }}">Henüz çekilmedi</small></button></div>@endforeach</div></div></div>
<div class="servis-aksiyonlar"><a href="{{ route('araclar.create') }}" class="btn btn-outline-secondary">Araç kartına dön</a><button class="btn btn-servis-ana">Servisi başlat ve iş emrini aç <i class="bi bi-arrow-right"></i></button></div></form></main>
<input id="qrInput" type="file" accept="image/*" capture="environment" hidden><input id="plakaInput" type="file" accept="image/*" capture="environment" hidden>
<script>
document.addEventListener('DOMContentLoaded',()=>{
    const sel=document.getElementById('aracId'),mid=document.getElementById('musteriId'),ara=document.getElementById('plakaAra'),durum=document.getElementById('taramaDurum'),qrInput=document.getElementById('qrInput'),plakaInput=document.getElementById('plakaInput');
    const normalize=value=>(value||'').toLocaleUpperCase('tr-TR').replace(/[^0-9A-ZÇĞİÖŞÜ]/g,'');
    function set(){mid.value=sel.options[sel.selectedIndex]?.dataset.musteri||''}
    function filtrele(){const q=normalize(ara.value);[...sel.options].forEach(o=>{o.hidden=!!q&&!normalize(o.dataset.plaka).includes(q)})}
    function aracSec(arac){const option=[...sel.options].find(o=>String(o.value)===String(arac.id));if(!option)throw new Error('Araç bu çalışma alanında bulunamadı.');sel.value=option.value;ara.value=option.dataset.plaka||arac.plaka||'';filtrele();set();sel.dispatchEvent(new Event('change'));durum.textContent='Araç bulundu: '+ara.value}
    async function qrDegeriOku(file){const bitmap=await createImageBitmap(file);try{if('BarcodeDetector' in window){const kodlar=await new BarcodeDetector({formats:['qr_code']}).detect(bitmap);if(kodlar[0]?.rawValue)return kodlar[0].rawValue}const {default:jsQR}=await import('https://cdn.jsdelivr.net/npm/jsqr@1.4.0/+esm');const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0);const image=context.getImageData(0,0,canvas.width,canvas.height);return jsQR(image.data,image.width,image.height)?.data||''}finally{bitmap.close?.()}}
    async function qrIsle(file){durum.textContent='QR kod okunuyor…';const ham=await qrDegeriOku(file);const token=ham.match(/\/arac\/([^/?#]+)/)?.[1]||ham.match(/\/qr-servis\/([^/?#]+)/)?.[1]||ham.trim();if(!token)throw new Error('Fotoğrafta geçerli QR kod bulunamadı.');const response=await fetch(@json(route('servis.qr.bul'))+'?token='+encodeURIComponent(token),{headers:{Accept:'application/json'}});const data=await response.json();if(!data.success)throw new Error('QR koduna ait araç bulunamadı.');aracSec(data.arac)}
    async function plakaMetniOku(file){const bitmap=await createImageBitmap(file);try{if('TextDetector' in window){const sonuclar=await new TextDetector().detect(bitmap);const metin=sonuclar.map(x=>x.rawValue).join(' ');if(metin.trim())return metin}}finally{bitmap.close?.()}const {createWorker}=await import('https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/+esm');const worker=await createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')durum.textContent='Plaka okunuyor… %'+Math.round((m.progress||0)*100)}});try{return (await worker.recognize(file)).data.text||''}finally{await worker.terminate()}}
    async function plakaIsle(file){durum.textContent='Plaka fotoğrafı analiz ediliyor…';const metin=normalize(await plakaMetniOku(file));const eslesen=[...sel.options].find(o=>o.dataset.plaka&&metin.includes(normalize(o.dataset.plaka)));if(eslesen){aracSec({id:eslesen.value,plaka:eslesen.dataset.plaka});return}const bulunan=metin.match(/(0[1-9]|[1-7][0-9]|8[01])[A-Z]{1,3}[0-9]{2,4}/)?.[0];if(!bulunan)throw new Error('Plaka okunamadı. Daha yakın ve net bir fotoğraf çekin.');ara.value=bulunan;filtrele();const option=[...sel.options].find(o=>normalize(o.dataset.plaka)===bulunan);if(option){aracSec({id:option.value,plaka:option.dataset.plaka})}else{durum.textContent='Plaka okundu: '+bulunan+' — kayıtlı araç eşleşmesi bulunamadı.'}}
    async function dosyaIsle(input,islem){const file=input.files?.[0];if(!file)return;try{await islem(file)}catch(error){durum.textContent=error.message||'Görüntü okunamadı.'}finally{input.value=''}}
    sel.addEventListener('change',set);set();if(sel.value){const option=sel.options[sel.selectedIndex];ara.value=option?.dataset.plaka||''}ara.addEventListener('input',filtrele);document.getElementById('qrButon').onclick=()=>qrInput.click();document.getElementById('plakaKamera').onclick=()=>plakaInput.click();qrInput.addEventListener('change',()=>dosyaIsle(qrInput,qrIsle));plakaInput.addEventListener('change',()=>dosyaIsle(plakaInput,plakaIsle));document.querySelectorAll('[data-kamera-hedef]').forEach(button=>{const input=document.getElementById(button.dataset.kameraHedef);const fotoDurum=document.getElementById('kamera-durum-'+input.id.replace('kamera-',''));button.addEventListener('click',()=>input.click());input.addEventListener('change',()=>{if(input.files?.length){fotoDurum.textContent='Fotoğraf hazır ✓';button.classList.add('border-warning')}})});
});
</script>
@endsection
