@extends('layouts.app')
@section('title','Servis Kabul | İZGİOS')
@section('content')
<section class="container py-4 servis-form"><div class="servis-form-hero"><div><div class="eyebrow">SERVİS AKIŞI · 3. ADIM</div><h1>Servis Kabul</h1><p>Araç teslim bilgilerini kaydedin; işlem tamamlanınca iş emri tamir ekranında açılır.</p></div><i class="bi bi-clipboard2-check"></i></div>
@include('components.servis-akisi', ['aktifAdim' => 3])
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<form action="{{ route('servis.kabul.store') }}" method="POST" enctype="multipart/form-data" class="corporate-form card">@csrf<input type="hidden" name="arac_id" id="arac_id"><input type="hidden" name="musteri_id" id="musteri_id">
<div class="card-body p-4 p-lg-5"><div class="form-section-title"><i class="bi bi-search"></i><div><h2>Aracı seçin</h2><p>Plaka ile arayın, listeden seçin veya QR okutun.</p></div></div>
<div class="kabul-grid kabul-search-grid"><div><label>Plaka ile ara</label><div class="plate-search"><input id="plaka" placeholder="Örn: 34 ABC 123" autocomplete="off"><button type="button" id="plakaAra" class="btn btn-outline-primary"><i class="bi bi-search"></i> Ara</button></div></div><div><label>Hızlı araç bulma</label><div class="scan-actions"><button type="button" id="qrOku" class="btn btn-outline-secondary"><i class="bi bi-qr-code-scan"></i> QR Oku</button><button type="button" id="kameraOku" class="btn btn-outline-secondary"><i class="bi bi-camera"></i> Plaka Kamera</button></div></div><div class="kabul-full"><label>Kayıtlı araçlar</label><select id="aracSelect"><option value="">Araç seçiniz</option>@foreach($araclar as $arac)<option value="{{ $arac->id }}" data-plaka="{{ $arac->plaka }}" data-marka="{{ $arac->marka }}" data-model="{{ $arac->model }}" data-yil="{{ $arac->model_yili }}" data-sase="{{ $arac->sase_no }}" data-musteriid="{{ $arac->musteri_id }}" data-musteri="{{ $arac->musteri?->ad_soyad }}" data-telefon="{{ $arac->musteri?->telefon }}">{{ $arac->plaka }} · {{ $arac->marka }} {{ $arac->model }} · {{ $arac->musteri?->ad_soyad }}</option>@endforeach</select></div><div class="kabul-full" id="aramaSonuclari"></div></div>
<div id="aracOzet" class="arac-ozet d-none mt-4"><div><span>PLAKA</span><strong id="bilgiPlaka">-</strong></div><div><span>ARAÇ</span><strong id="bilgiArac">-</strong></div><div><span>MÜŞTERİ</span><strong id="bilgiMusteri">-</strong></div><div><span>TELEFON</span><strong id="bilgiTelefon">-</strong></div></div>
<hr class="my-4"><div class="form-section-title"><i class="bi bi-clipboard-check"></i><div><h2>Servis giriş bilgileri</h2><p>Kabul saati otomatik olarak kaydedilir.</p></div></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="kabul-grid kabul-two-grid"><div><label>Giriş Kilometresi <sup>*</sup></label><input type="number" name="giris_km" min="0" value="{{ old('giris_km') }}" required placeholder="Örn: 125000"></div><div><label>Öncelik</label><select name="oncelik"><option value="Normal">Normal</option><option value="Acil">Acil</option><option value="Bekleyen">Bekleyen</option></select></div><div><label>Müşteri Şikayeti <sup>*</sup></label><textarea name="sikayet" rows="4" required placeholder="Müşterinin talep ve şikâyetini yazın">{{ old('sikayet') }}</textarea></div><div><label>İlk Kontrol Notu</label><textarea name="usta_notu" rows="4" placeholder="İlk gözlem veya kontrol notu">{{ old('usta_notu') }}</textarea></div></div>
<hr class="my-4"><div class="form-section-title"><i class="bi bi-key"></i><div><h2>Teslim ve araç durumu</h2><p>Araç tesliminde kayıt altına alınacak bilgiler.</p></div></div><div class="kabul-grid kabul-three-grid"><div><label>Yakıt Seviyesi</label><select name="yakit_seviyesi"><option value="">Belirtilmedi</option><option>1/4</option><option>1/2</option><option>3/4</option><option>1/1</option></select></div><div><label>Anahtar Durumu</label><select name="anahtar_durumu"><option>Teslim Alındı</option><option>Yok</option></select></div><div><label>Ruhsat Araçta mı?</label><select name="ruhsat_aracta"><option value="1">Var</option><option value="0">Yok</option></select></div><div class="kabul-full"><label>Araç Mevcut Durum Notu</label><textarea name="arac_durum_notu" rows="3" placeholder="Araç üzerinde görülen mevcut durum notları">{{ old('arac_durum_notu') }}</textarea></div></div>
<hr class="my-4"><div class="form-section-title"><i class="bi bi-camera"></i><div><h2>Araç dış fotoğrafları</h2><p>Telefon ve tablette doğrudan arka kamerayı açar.</p></div></div><div class="kabul-photo-grid">@foreach(['on'=>'Ön görünüm','sag'=>'Sağ görünüm','sol'=>'Sol görünüm','arka'=>'Arka görünüm'] as $key=>$title)<label class="kamera-kart"><input type="file" accept="image/*" capture="environment" name="fotograflar[{{ $key }}]"><i class="bi bi-camera-fill"></i><b>{{ $title }}</b><small>Kamerayı aç</small></label>@endforeach</div></div>
<div class="form-footer"><a class="btn btn-light" href="{{ route('araclar.index') }}"><i class="bi bi-arrow-left"></i> Araçlara Dön</a><button class="btn btn-primary" type="submit">Servise Al ve Tamir Ekranını Aç <i class="bi bi-arrow-right"></i></button></div></form></section>
@include('components.servis-form-style')
<style>.kabul-grid{display:grid;gap:1rem}.kabul-search-grid{grid-template-columns:1.35fr 1fr}.kabul-two-grid{grid-template-columns:1fr 1fr}.kabul-three-grid{grid-template-columns:repeat(3,1fr)}.kabul-full{grid-column:1/-1}.plate-search{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.65rem}.plate-search .btn{min-width:98px}.scan-actions{display:grid;grid-template-columns:1fr 1fr;gap:.65rem}.scan-actions .btn{width:100%;min-height:44px}.kabul-photo-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem}.arac-ozet{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem;padding:1rem;border:1px solid #d5e5f2;border-radius:14px;background:#f6fbff}.arac-ozet div{display:flex;flex-direction:column;gap:.3rem}.arac-ozet span{font-size:.7rem;color:#68809b;font-weight:800}.arac-ozet strong{color:#142b4e}.kamera-kart{display:flex!important;min-height:118px;align-items:center;justify-content:center;flex-direction:column;gap:.4rem;border:1px dashed #79a6cc;border-radius:12px;background:#f8fcff;color:#1764b9;cursor:pointer}.kamera-kart input{display:none}.kamera-kart i{font-size:1.45rem}.kamera-kart small{color:#6d819b}.tema-koyu .arac-ozet{background:#202f49;border-color:#41526e}.tema-koyu .arac-ozet strong{color:#edf4ff}.tema-koyu .kamera-kart{background:#202f49}@media(max-width:900px){.kabul-search-grid,.kabul-three-grid,.kabul-photo-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.kabul-search-grid,.kabul-two-grid,.kabul-three-grid,.kabul-photo-grid,.plate-search,.scan-actions{grid-template-columns:1fr}.plate-search .btn{width:100%}.arac-ozet{grid-template-columns:repeat(2,1fr)}}</style>
<script>const sec=(a)=>document.querySelector(a);function aracSec(arac){sec('#arac_id').value=arac.id;sec('#musteri_id').value=arac.musteri_id||'';sec('#bilgiPlaka').textContent=arac.plaka||'-';sec('#bilgiArac').textContent=((arac.marka||'')+' '+(arac.model||'')).trim()||'-';sec('#bilgiMusteri').textContent=arac.musteri?.ad_soyad||arac.musteri_adi||'-';sec('#bilgiTelefon').textContent=arac.musteri?.telefon||arac.telefon||'-';sec('#aracOzet').classList.remove('d-none')}sec('#aracSelect').addEventListener('change',function(){let o=this.options[this.selectedIndex];if(!o.value)return;aracSec({id:o.value,musteri_id:o.dataset.musteriid,plaka:o.dataset.plaka,marka:o.dataset.marka,model:o.dataset.model,musteri:{ad_soyad:o.dataset.musteri,telefon:o.dataset.telefon}})});sec('#plakaAra').onclick=async()=>{let q=sec('#plaka').value.trim();if(!q)return;let sonuc=await fetch('/servis-kabul/arac-bul?plaka='+encodeURIComponent(q)).then(r=>r.json());let alan=sec('#aramaSonuclari');alan.innerHTML=sonuc.length?sonuc.map(x=>`<button class="btn btn-light border me-2 mb-2" type="button" data-id="${x.id}">${x.plaka} · ${x.marka||''} ${x.model||''}</button>`).join(''):'<small class="text-muted">Araç bulunamadı.</small>';alan.querySelectorAll('button').forEach(b=>b.onclick=()=>aracSec(sonuc.find(x=>x.id==b.dataset.id)))};sec('#kameraOku').onclick=()=>{let x=document.createElement('input');x.type='file';x.accept='image/*';x.capture='environment';x.onchange=()=>alert('Fotoğraf alındı. Tarayıcınız plaka metnini otomatik algılamıyorsa plakayı arama alanına yazın.');x.click()};const pre=@json($seciliAracId ?? null);if(pre){sec('#aracSelect').value=pre;sec('#aracSelect').dispatchEvent(new Event('change'))}</script>
@endsection
