@extends('layouts.app')
@section('title','Servis Kabul | İZGİOS')
@section('content')
<style>
    .kabul-teslim-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }
    .kabul-kamera-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 10px; }
    .kabul-kamera-girdi { display: none !important; }
    .kabul-kamera-btn { display: flex; min-height: 66px; flex-direction: column; align-items: center; justify-content: center; gap: 3px; padding: 8px; border: 1px solid #d2deed; border-radius: 12px; background: #f8fbff; color: #163d6c; font-weight: 800; }
    .kabul-kamera-btn:hover { border-color: #dfb536; background: #fff9e7; color: #142b4e; }
    .kabul-kamera-btn i { color: #c89d18; font-size: 1.35rem; }
    .kabul-kamera-durum { color: #6b7f99; font-size: .74rem; font-weight: 600; }
    .servis-aksiyonlar { display: flex; justify-content: center; align-items: center; gap: 14px; flex-wrap: wrap; }
    .kabul-tarama-btn { min-height: 44px; padding: 0 14px; border: 1px solid #e3b82e; border-radius: 11px; background: #e3b82e; color: #fff; font-weight: 850; }
    .kabul-tarama-btn--plaka { background: #fff; color: #163d6c; border-color: #cbd9ea; }
    .kabul-arama-sonuclari { display: grid; gap: 7px; margin-top: 8px; padding: 8px; border: 1px solid #d5e0ee; border-radius: 12px; background: #fff; box-shadow: 0 12px 28px rgba(15, 39, 75, .1); }
    .kabul-arama-sonuclari[hidden] { display: none; }
    .kabul-arama-sonucu { width: 100%; padding: 10px 12px; border: 0; border-radius: 9px; background: #f4f7fb; color: #183b66; text-align: left; font-weight: 750; cursor: pointer; }
    .kabul-arama-sonucu:hover { background: #fff4c8; }
    @media (max-width: 900px) { .kabul-teslim-grid { grid-template-columns: 1fr; } }
    @media (max-width: 700px) { .kabul-kamera-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; }.kabul-kamera-btn{min-height:58px;flex-direction:row;gap:7px}.kabul-kamera-durum{display:none} }
</style>
<main class="container py-4"><x-servis-yeni-tasarim :adim="3" baslik="Servis kabul" aciklama="Araç teslimini hızlıca kaydedin; iş emri bir sonraki ekranda başlar." />
@if($errors->any())<div class="alert alert-danger">Araç, müşteri ve şikayet alanlarını kontrol edin.</div>@endif
<form method="POST" action="{{ route('servis.kabul.store') }}" enctype="multipart/form-data" class="servis-sayfa-kart" id="kabulForm">@csrf
<div class="kart-baslik"><div><h2>1. Araç seçimi</h2><p>Plaka arayın, listeden seçin veya tablet/telefonda QR okutun.</p></div><a class="btn btn-sm btn-outline-primary" href="{{ route('musteriler.create') }}"><i class="bi bi-person-plus-fill"></i> Yeni müşteri oluştur</a></div>
<div class="servis-form-grid"><div class="tam"><label>Araç ara</label><div class="input-group"><input id="plakaAra" class="form-control" placeholder="Plaka, marka/model, müşteri adı veya telefon"><button class="kabul-tarama-btn" type="button" id="aramaButon"><i class="bi bi-search"></i> Ara</button><button class="kabul-tarama-btn" type="button" id="qrButon"><i class="bi bi-qr-code-scan"></i> QR oku</button><button class="kabul-tarama-btn kabul-tarama-btn--plaka" type="button" id="plakaKamera"><i class="bi bi-camera"></i> Plaka kamera</button></div><div class="kabul-arama-sonuclari" id="aramaSonuclari" hidden></div><div class="servis-bilgi-notu mt-2">Yazdıkça eşleşen araçlar görünür. Plaka, harf/rakam, müşteri adı veya telefonla arayabilirsiniz.</div><div class="servis-bilgi-notu mt-1" id="taramaDurum" role="status" aria-live="polite"></div></div><div class="tam"><label>Kayıtlı araç <span class="text-danger">*</span></label><select class="form-select" name="arac_id" id="aracId" required><option value="">Araç seçin</option>@foreach($araclar as $arac)<option value="{{ $arac->id }}" data-musteri="{{ $arac->musteri_id }}" data-plaka="{{ $arac->plaka }}" data-telefon="{{ $arac->musteri?->telefon }} {{ $arac->musteri?->telefon2 }}" @selected(old('arac_id',$seciliAracId)==$arac->id)>{{ $arac->plaka }} · {{ $arac->marka }} {{ $arac->model }} · {{ $arac->musteri?->ad_soyad }}</option>@endforeach</select><input type="hidden" name="musteri_id" id="musteriId" value="{{ old('musteri_id') }}"></div><div><label>Giriş kilometresi</label><input class="form-control" type="number" name="giris_km" min="0" inputmode="numeric" value="{{ old('giris_km') }}" placeholder="KM"></div><div><label>Öncelik</label><select class="form-select" name="oncelik"><option value="Normal">Normal</option><option value="Acil">Acil</option><option value="Bekleyen">Parça / onay bekliyor</option></select></div><div class="tam"><label>Müşteri şikayeti / talebi <span class="text-danger">*</span></label><textarea class="form-control" name="sikayet" required placeholder="Müşterinin talebini kısa ve anlaşılır biçimde yazın">{{ old('sikayet') }}</textarea></div></div>
<div class="kart-baslik"><h2>2. Teslim bilgileri</h2><p>Bu bilgiler sadece teslim anını belgelemek için kaydedilir.</p></div><div class="servis-form-grid kabul-teslim-grid"><div><label>Yakıt seviyesi</label><select class="form-select" name="yakit_seviyesi"><option value="">Belirtilmedi</option><option>Boş</option><option>1/4</option><option>1/2</option><option>3/4</option><option>Dolu</option></select></div><div><label>Anahtar durumu</label><select class="form-select" name="anahtar_durumu"><option value="">Seçin</option><option value="ARAÇTA">Araçta</option><option value="YOK">Yok</option></select></div><div><label>Ruhsat araçta mı?</label><select class="form-select" name="ruhsat_aracta"><option value="">Seçin</option><option value="1">Evet</option><option value="0">Hayır</option></select></div><div class="tam"><label>İlk kabul notu</label><textarea class="form-control" name="arac_durum_notu" placeholder="Gözle görülen durum veya teslim notu"></textarea></div><div class="tam"><label><i class="bi bi-camera-fill me-1"></i>Araç fotoğrafları</label><p class="servis-bilgi-notu mb-2">Yönü seçin; telefon ve tablette kamera, bilgisayarda dosya seçimi açılır.</p><div class="kabul-kamera-grid">@foreach(['on'=>'Ön','sag'=>'Sağ','sol'=>'Sol','arka'=>'Arka'] as $key=>$label)<div><input id="kamera-{{ $key }}" class="kabul-kamera-girdi" type="file" name="fotograflar[{{ $key }}]" accept="image/*" capture="environment" hidden><button type="button" class="kabul-kamera-btn w-100" data-kamera-hedef="kamera-{{ $key }}"><i class="bi bi-camera-fill"></i><span>{{ $label }}</span><small class="kabul-kamera-durum" id="kamera-durum-{{ $key }}">Fotoğraf ekle</small></button></div>@endforeach</div></div></div>
<div class="servis-aksiyonlar"><a href="{{ route('araclar.create') }}" class="btn btn-outline-secondary">Araç kartına dön</a><button class="btn btn-servis-ana">Servisi başlat ve iş emrini aç <i class="bi bi-arrow-right"></i></button></div></form></main>
<input id="qrInput" type="file" accept="image/*" capture="environment" hidden><input id="plakaInput" type="file" accept="image/*" capture="environment" hidden>
<script>
document.addEventListener('DOMContentLoaded',()=>{
    const sel=document.getElementById('aracId'),mid=document.getElementById('musteriId'),ara=document.getElementById('plakaAra'),aramaButon=document.getElementById('aramaButon'),aramaSonuclari=document.getElementById('aramaSonuclari'),durum=document.getElementById('taramaDurum'),qrInput=document.getElementById('qrInput'),plakaInput=document.getElementById('plakaInput');
    const normalize=value=>(value||'').toLocaleUpperCase('tr-TR').replace(/[^0-9A-ZÇĞİÖŞÜ]/g,'');
    function set(){mid.value=sel.options[sel.selectedIndex]?.dataset.musteri||''}
    function filtrele(goster=true){const q=normalize(ara.value),secenekler=[...sel.options].filter(o=>o.value),eslesenler=secenekler.filter(o=>!q||normalize(o.textContent+' '+(o.dataset.telefon||'')).includes(q));secenekler.forEach(o=>{o.hidden=!!q&&!eslesenler.includes(o)});aramaSonuclari.replaceChildren();if(!q||!goster){aramaSonuclari.hidden=true;return eslesenler}eslesenler.slice(0,15).forEach(option=>{const button=document.createElement('button');button.type='button';button.className='kabul-arama-sonucu';button.textContent=option.textContent.trim()+(option.dataset.telefon?' · '+option.dataset.telefon.trim():'');button.addEventListener('click',()=>aracSec({id:option.value,plaka:option.dataset.plaka}));aramaSonuclari.append(button)});aramaSonuclari.hidden=false;durum.textContent=eslesenler.length?eslesenler.length+' araç bulundu.': 'Eşleşen araç bulunamadı.';return eslesenler}
    function aracSec(arac){const option=[...sel.options].find(o=>String(o.value)===String(arac.id));if(!option)throw new Error('Araç bu çalışma alanında bulunamadı.');sel.value=option.value;ara.value=option.dataset.plaka||arac.plaka||'';filtrele(false);set();sel.dispatchEvent(new Event('change'));durum.textContent='Araç bulundu: '+ara.value}
    function goruntuTuvali(bitmap,donus=0,gri=false,sinir=1600){const oran=Math.min(1,sinir/Math.max(bitmap.width,bitmap.height)),w=Math.max(1,Math.round(bitmap.width*oran)),h=Math.max(1,Math.round(bitmap.height*oran)),dikey=donus%180!==0,canvas=document.createElement('canvas');canvas.width=dikey?h:w;canvas.height=dikey?w:h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(donus*Math.PI/180);ctx.drawImage(bitmap,-w/2,-h/2,w,h);ctx.setTransform(1,0,0,1,0,0);if(gri){const im=ctx.getImageData(0,0,canvas.width,canvas.height),d=im.data;for(let i=0;i<d.length;i+=4){const y=d[i]*.299+d[i+1]*.587+d[i+2]*.114,v=y>150?255:y<75?0:Math.max(0,Math.min(255,(y-128)*1.8+128));d[i]=d[i+1]=d[i+2]=v}ctx.putImageData(im,0,0)}return canvas}
    async function modulYukle(adresler){let hata;for(const adres of adresler){try{return await import(adres)}catch(e){hata=e}}throw new Error('Okuma kütüphanesi yüklenemedi. İnternet bağlantısını kontrol edin.',{cause:hata})}
    async function qrDegeriOku(file){const bitmap=await createImageBitmap(file);try{const tuvaller=[0,90,180,270].map(a=>goruntuTuvali(bitmap,a));if('BarcodeDetector' in window){const detector=new BarcodeDetector({formats:['qr_code']});for(const hedef of [bitmap,...tuvaller]){const kodlar=await detector.detect(hedef).catch(()=>[]);if(kodlar[0]?.rawValue)return kodlar[0].rawValue}}const {default:jsQR}=await modulYukle(['https://cdn.jsdelivr.net/npm/jsqr@1.4.0/+esm','https://esm.sh/jsqr@1.4.0']);for(const canvas of tuvaller){const ctx=canvas.getContext('2d',{willReadFrequently:true}),image=ctx.getImageData(0,0,canvas.width,canvas.height);for(const inversionAttempts of ['attemptBoth','invertFirst']){const sonuc=jsQR(image.data,image.width,image.height,{inversionAttempts});if(sonuc?.data)return sonuc.data}}return ''}finally{bitmap.close?.()}}
    async function qrIsle(file){durum.textContent='QR kod okunuyor…';const ham=await qrDegeriOku(file);const token=ham.match(/\/arac\/([^/?#]+)/)?.[1]||ham.match(/\/qr-servis\/([^/?#]+)/)?.[1]||ham.trim();if(!token)throw new Error('Fotoğrafta geçerli QR kod bulunamadı.');const response=await fetch(@json(route('servis.qr.bul'))+'?token='+encodeURIComponent(token),{headers:{Accept:'application/json'}});const data=await response.json();if(!data.success)throw new Error('QR koduna ait araç bulunamadı.');aracSec(data.arac)}
    async function plakaMetniOku(file){const bitmap=await createImageBitmap(file);try{const canvas=goruntuTuvali(bitmap,0,true);if('TextDetector' in window){const sonuclar=await new TextDetector().detect(canvas).catch(()=>[]),metin=sonuclar.map(x=>x.rawValue).join(' ');if(metin.trim())return metin}const {createWorker}=await modulYukle(['https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/+esm','https://esm.sh/tesseract.js@5.1.1']);const worker=await createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')durum.textContent='Plaka okunuyor… %'+Math.round((m.progress||0)*100)}});try{await worker.setParameters({tessedit_char_whitelist:'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ',tessedit_pageseg_mode:'7',preserve_interword_spaces:'1'});const ilk=(await worker.recognize(canvas)).data.text||'';if(normalize(ilk).length>=5)return ilk;await worker.setParameters({tessedit_pageseg_mode:'6'});return (await worker.recognize(file)).data.text||ilk}finally{await worker.terminate()}}finally{bitmap.close?.()}}
    async function plakaIsle(file){durum.textContent='Plaka fotoğrafı analiz ediliyor…';const metin=normalize(await plakaMetniOku(file)).replace(/[OQ](?=\d)/g,'0').replace(/(?<=\d)[OQ]/g,'0');const secenekler=[...sel.options].filter(o=>o.dataset.plaka);const eslesen=secenekler.find(o=>metin.includes(normalize(o.dataset.plaka)))||secenekler.find(o=>{const p=normalize(o.dataset.plaka);return p.length>=6&&metin.includes(p.slice(0,-1))});if(eslesen){aracSec({id:eslesen.value,plaka:eslesen.dataset.plaka});return}const bulunan=metin.match(/(0[1-9]|[1-7][0-9]|8[01])[A-Z]{1,3}[0-9]{2,4}/)?.[0];if(!bulunan)throw new Error('Plaka okunamadı. Plakayı kadraja yakın, düz ve gölgesiz çekin; isterseniz üstteki alana elle yazın.');ara.value=bulunan;filtrele();const option=secenekler.find(o=>normalize(o.dataset.plaka)===bulunan);if(option){aracSec({id:option.value,plaka:option.dataset.plaka})}else{durum.textContent='Plaka okundu: '+bulunan+' — kayıtlı araç eşleşmesi bulunamadı.'}}
    async function dosyaIsle(input,islem){const file=input.files?.[0];if(!file)return;try{await islem(file)}catch(error){durum.textContent=error.message||'Görüntü okunamadı.'}finally{input.value=''}}
    async function fotografiKucult(file){if(!file.type.startsWith('image/'))return file;const bitmap=await createImageBitmap(file);try{const canvas=goruntuTuvali(bitmap,0,false,1000),blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Fotoğraf hazırlanamadı.')),'image/jpeg',.65));return new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg',lastModified:Date.now()})}finally{bitmap.close?.()}}
    sel.addEventListener('change',set);set();if(sel.value){const option=sel.options[sel.selectedIndex];ara.value=option?.dataset.plaka||''}ara.addEventListener('input',()=>filtrele());ara.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();filtrele()}});aramaButon.addEventListener('click',()=>filtrele());document.getElementById('qrButon').onclick=()=>qrInput.click();document.getElementById('plakaKamera').onclick=()=>plakaInput.click();qrInput.addEventListener('change',()=>dosyaIsle(qrInput,qrIsle));plakaInput.addEventListener('change',()=>dosyaIsle(plakaInput,plakaIsle));document.querySelectorAll('[data-kamera-hedef]').forEach(button=>{const input=document.getElementById(button.dataset.kameraHedef);const fotoDurum=document.getElementById('kamera-durum-'+input.id.replace('kamera-',''));button.addEventListener('click',()=>input.click());input.addEventListener('change',async()=>{if(!input.files?.length)return;fotoDurum.textContent='Fotoğraf hazırlanıyor…';button.disabled=true;try{const file=await fotografiKucult(input.files[0]),transfer=new DataTransfer();transfer.items.add(file);input.files=transfer.files;fotoDurum.textContent='Fotoğraf hazır ✓';button.classList.add('border-warning')}catch(error){input.value='';fotoDurum.textContent=error.message||'Fotoğraf hazırlanamadı.'}finally{button.disabled=false}})});
});
</script>
@endsection
