@php
    $baglanti = $personelBaglantisi ?? null;
    $secilenFirmaId = old('firma_id', $baglanti?->firma_id);
    $secilenSubeId = old('sube_id', $baglanti?->sube_id ?: 'firma_merkez');
    $subeVerisi = $firmalar->mapWithKeys(fn ($firma) => [$firma->id => $firma->subeler->map(fn ($sube) => ['id' => $sube->id, 'ad' => $sube->sube_adi])->values()]);
@endphp
<div class="row g-3">
    <div class="col-12"><div class="personel-baglanti-baslik"><div><i class="bi bi-buildings"></i> Çalışma Bağlantısı</div><small>“Firma Merkezi” seçimi personeli doğrudan firmaya bağlar; şube seçimi yalnız ilgili şubede çalıştırır.</small></div></div>
    <div class="col-md-6"><label class="form-label" for="firma_id">Firma</label><select id="firma_id" name="firma_id" required><option value="">Firma seçiniz</option>@foreach($firmalar as $firma)<option value="{{ $firma->id }}" @selected((string) $secilenFirmaId === (string) $firma->id)>{{ $firma->gosterim_adi }}</option>@endforeach</select>@error('firma_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="sube_id">Çalışma yeri</label><select id="sube_id" name="sube_id" required disabled><option value="">Önce firma seçiniz</option></select><div class="form-text" id="sube-yardim">Firma Merkezi seçimi, personeli firma çalışanı olarak kaydeder.</div>@error('sube_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    <div class="col-12"><hr class="my-1"></div>
    <div class="col-md-6"><label class="form-label" for="name">Ad</label><input id="name" type="text" name="name" value="{{ old('name', $kullanici?->name) }}" required></div>
    <div class="col-md-6"><label class="form-label" for="surname">Soyad</label><input id="surname" type="text" name="surname" value="{{ old('surname', $kullanici?->surname) }}" required></div>
    <div class="col-md-6"><label class="form-label" for="email">E-posta</label><input id="email" type="email" name="email" value="{{ old('email', $kullanici?->email) }}" required></div>
    <div class="col-md-6"><label class="form-label" for="dogum_tarihi">Doğum tarihi</label><input id="dogum_tarihi" type="date" name="dogum_tarihi" value="{{ old('dogum_tarihi', $kullanici?->dogum_tarihi?->format('Y-m-d')) }}"></div>
    <div class="col-md-6"><label class="form-label" for="phone">Telefon</label><input id="phone" type="tel" name="phone" value="{{ old('phone', $kullanici?->phone) }}"></div>
    <div class="col-md-6"><label class="form-label" for="tc_no">T.C. kimlik no</label><input id="tc_no" name="tc_no" maxlength="11" value="{{ old('tc_no', $kullanici?->tc_no) }}"></div>
    <div class="col-md-6"><label class="form-label" for="role">Personel rolü</label><select id="role" name="role" required><option value="">Rol seçiniz</option>@foreach($roller as $kod => $ad) @if(!(auth()->user()?->isIk() && in_array($kod, ['sistem_yoneticisi','admin'], true)))<option value="{{ $kod }}" @selected(old('role',$kullanici?->role)===$kod)>{{ $ad }}</option>@endif @endforeach</select></div>
    <div class="col-md-6"><label class="form-label" for="password">{{ $kullanici ? 'Yeni şifre (değişmeyecekse boş bırakın)' : 'Şifre' }}</label><input id="password" type="password" name="password" minlength="8" {{ $kullanici ? '' : 'required' }}><div class="form-text">En az 8 karakter kullanın.</div>@error('password')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="password_confirmation">Şifre tekrar</label><input id="password_confirmation" type="password" name="password_confirmation" minlength="8" {{ $kullanici ? '' : 'required' }}>@error('password_confirmation')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    <div class="col-12"><div class="alert alert-info mb-0"><strong>Rol bilgisi:</strong> Menü ve ekran erişimleri atanan role göre otomatik belirlenir.</div></div>
</div>
<style>.personel-baglanti-baslik{padding:15px 18px;border:1px solid #dbe6f8;border-radius:12px;background:#f6f9ff;display:flex;justify-content:space-between;align-items:center;color:#112d57;font-weight:700}.personel-baglanti-baslik small{font-weight:500;color:#5c6f89}@media(max-width:700px){.personel-baglanti-baslik{display:block}.personel-baglanti-baslik small{display:block;margin-top:5px}}</style>
<script>document.addEventListener('DOMContentLoaded',()=>{const firmalar=@json($subeVerisi),firma=document.getElementById('firma_id'),sube=document.getElementById('sube_id'),yardim=document.getElementById('sube-yardim'),secili=@json((string)$secilenSubeId),demoFirma=@json($firmalar->first(fn($firma)=>mb_strtoupper($firma->unvan)==='DEMO OTOMOTİV')?->id);const yukle=()=>{const liste=firmalar[firma.value]||[];sube.innerHTML='';sube.disabled=!firma.value;if(!firma.value){sube.add(new Option('Önce firma seçiniz',''));yardim.textContent='Önce firmanızı seçin.';return}sube.add(new Option('Firma Merkezi · Firma çalışanı','firma_merkez'));if(liste.length){sube.add(new Option('Şube seçiniz',''));liste.forEach(x=>sube.add(new Option(x.ad,x.id)))}const gecerli=secili==='firma_merkez'||liste.some(x=>String(x.id)===secili);sube.value=gecerli?secili:'firma_merkez';if(String(firma.value)===String(demoFirma)){const e=document.getElementById('email'),p=document.getElementById('password'),t=document.getElementById('password_confirmation');if(!e.value)e.value='demo@izgios.com';if(!p.value)p.value='demo12345';if(!t.value)t.value='demo12345';yardim.textContent='Demo Otomotiv seçildi: demo giriş bilgileri otomatik dolduruldu.'}else{bilgi()}};const bilgi=()=>yardim.textContent=sube.value==='firma_merkez'?'Firma Merkezi seçildi: personel doğrudan firma çalışanı olarak kaydedilecek.':'Personel yalnız seçilen şubeye bağlı çalışacak.';firma.addEventListener('change',yukle);sube.addEventListener('change',bilgi);yukle()});</script>
