@extends('layouts.app')

@section('title', $durum === 'aktif' ? 'Aktif Personel' : 'Pasif Personel')

@section('content')
<style>
    .personel-page{max-width:1280px;margin:0 auto}.personel-page__head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:21px}.personel-page__head h1{margin:0;color:#17233c;font-size:26px;font-weight:800}.personel-page__head h1 i{color:#2563eb;margin-right:7px}.personel-page__head p{margin:7px 0 0;color:#64748b;font-size:14px}.personel-page__new{min-height:42px;padding:10px 14px;border-radius:10px;background:#2563eb;color:#fff;text-decoration:none;display:inline-flex;align-items:center;gap:7px;font-size:13px;font-weight:800}.personel-tabs{display:flex;gap:9px;margin-bottom:18px}.personel-tabs a{padding:10px 14px;border-radius:10px;text-decoration:none;font-size:13px;font-weight:800;background:#e2e8f0;color:#475569}.personel-tabs a.is-active{background:#2563eb;color:#fff}.personel-list{background:#fff;border:1px solid #e5eaf1;border-radius:18px;box-shadow:0 6px 20px rgba(15,23,42,.05);overflow:auto}.personel-table{width:100%;min-width:760px;border-collapse:collapse}.personel-table th,.personel-table td{padding:14px 16px;text-align:left;border-bottom:1px solid #edf1f5;font-size:13px}.personel-table th{color:#718096;font-size:11px;text-transform:uppercase}.personel-table td{color:#334155}.personel-table td strong{color:#1e293b}.personel-role,.personel-status{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:800;background:#e2e8f0;color:#475569}.personel-status--aktif{background:#dcfce7;color:#15803d}.personel-status--pasif{background:#fee2e2;color:#b91c1c}.personel-actions{display:flex;gap:7px}.personel-actions a,.personel-actions button{height:34px;min-width:34px;padding:0 9px;border:0;border-radius:8px;display:flex;align-items:center;justify-content:center;cursor:pointer}.personel-actions a{background:#dbeafe;color:#1d4ed8}.personel-actions button{background:#fee2e2;color:#b91c1c}.personel-actions .personel-activate{background:#dcfce7;color:#15803d}.personel-empty{padding:42px;text-align:center;color:#64748b}@media(max-width:680px){.personel-page__head{flex-direction:column}.personel-page__new{width:100%;justify-content:center}}
</style>
<section class="personel-page"><header class="personel-page__head"><div><h1><i class="bi bi-people-fill"></i> {{ $durum === 'aktif' ? 'Aktif Personel' : 'Pasif Personel' }}</h1><p>Personel kayıtları durumlarına göre ayrı ekranlarda tutulur.</p></div><a class="personel-page__new" href="{{ route('kullanicilar.create') }}"><i class="bi bi-person-plus-fill"></i> Yeni Personel</a></header><nav class="personel-tabs"><a class="{{ $durum === 'aktif' ? 'is-active' : '' }}" href="{{ route('kullanicilar.aktifler') }}">Aktif Personel</a><a class="{{ $durum === 'pasif' ? 'is-active' : '' }}" href="{{ route('kullanicilar.pasifler') }}">Pasif Personel</a></nav>@if(session('success'))<div class="alert-success">{{ session('success') }}</div>@endif@if(session('error'))<div class="alert-danger">{{ session('error') }}</div>@endif<div class="personel-list"><table class="personel-table"><thead><tr><th>Personel</th><th>İletişim</th><th>Rol</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>@forelse($kullanicilar as $kullanici)<tr><td><strong>{{ $kullanici->tamAdi() }}</strong><small style="display:block;color:#8490a2">{{ $kullanici->username }}</small></td><td>{{ $kullanici->phone ?: '-' }}<small style="display:block;color:#8490a2">{{ $kullanici->email }}</small></td><td><span class="personel-role">{{ $kullanici->rolAdi() }}</span></td><td><span class="personel-status personel-status--{{ $kullanici->status }}">{{ ucfirst($kullanici->status) }}</span></td><td><div class="personel-actions"><a href="{{ route('kullanicilar.edit', $kullanici) }}" aria-label="Personeli düzenle"><i class="bi bi-pencil"></i></a>@if($durum === 'aktif')<form method="POST" action="{{ route('kullanicilar.pasif', $kullanici) }}">@csrf @method('PATCH')<button type="submit" aria-label="Pasif yap"><i class="bi bi-person-x"></i></button></form>@else<form method="POST" action="{{ route('kullanicilar.aktif', $kullanici) }}">@csrf @method('PATCH')<button class="personel-activate" type="submit" aria-label="Aktif yap"><i class="bi bi-person-check"></i></button></form>@endif</div></td></tr>@empty<tr><td colspan="5"><div class="personel-empty">Bu listede personel bulunmuyor.</div></td></tr>@endforelse</tbody></table></div></section>
@endsection
