@extends('layouts.app')
@section('title','Rapor Merkezi')
@section('content')
<style>
.reports{max-width:1320px;margin:auto}.reports-head{padding:30px;border-radius:22px;background:linear-gradient(120deg,#10264b,#0c766f);color:#fff;box-shadow:0 16px 34px #0f254224}.reports-head p{margin:8px 0 0;color:#d7fffa}.report-picker,.report-card{background:#fff;border:1px solid #dce6f3;border-radius:18px;box-shadow:0 8px 22px #0f25410d}.report-picker{padding:24px;margin-top:20px}.reports-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:18px}.report-card{padding:20px}.report-card i{font-size:25px;color:#1d4ed8}.report-card span{display:block;color:#637694;margin-top:12px}.report-card strong{display:block;font-size:26px;margin-top:5px;color:#10264b}.report-types{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:18px}.report-type{display:block;border:1px solid #dbe5f1;border-radius:12px;padding:14px;cursor:pointer;transition:.15s}.report-type:hover,.report-type:has(input:checked){border-color:#ddb52b;background:#fff9df;box-shadow:0 4px 14px #d3a7181c}.report-type input{margin-right:7px}@media(max-width:800px){.reports-grid,.report-types{grid-template-columns:1fr}.report-picker{padding:16px}}
</style>
<section class="reports">
 <header class="reports-head"><h1 class="h3 mb-1"><i class="bi bi-bar-chart-fill"></i> Ayrıntılı Rapor Merkezi</h1><p>{{ $firmaAdi }} · Raporlar seçilen dönem ve yetkiniz kapsamındaki gerçek kayıtlarla hazırlanır.</p></header>
 @php($rol=auth()->user()->role)
 <form class="report-picker" method="POST" action="{{ route('raporlar.al') }}">@csrf
  <div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">Rapor türünü seçin</h2><small class="text-muted">Özet, hareket listesi, uyarılar ve kontrol noktaları birlikte oluşturulur.</small></div><i class="bi bi-file-earmark-bar-graph fs-2 text-warning"></i></div>
  <div class="report-types">
   @if(in_array($rol,['sistem_yoneticisi','admin','muhasebe']))<label class="report-type"><input type="radio" name="tur" value="finans" checked><strong>Finans ve muhasebe</strong><small class="d-block text-muted mt-1">Gelir, gider, nakit sonucu ve fiş hareketleri</small></label><label class="report-type"><input type="radio" name="tur" value="cari"><strong>Cari hesaplar</strong><small class="d-block text-muted mt-1">Bakiye, borç/alacak ve dönem hareketi</small></label>@endif
   @if(in_array($rol,['sistem_yoneticisi','admin','ofis','usta']))<label class="report-type"><input type="radio" name="tur" value="servis" @if(!in_array($rol,['sistem_yoneticisi','admin','muhasebe'])) checked @endif><strong>Servis operasyonu</strong><small class="d-block text-muted mt-1">İş emri, durum, işçilik, parça ve ciro</small></label>@endif
   @if(in_array($rol,['sistem_yoneticisi','admin','ik']))<label class="report-type"><input type="radio" name="tur" value="ik" @if($rol==='ik') checked @endif><strong>İK ve personel</strong><small class="d-block text-muted mt-1">Personel, bordro, mesai ve ücret kartları</small></label>@endif
   @if(in_array($rol,['sistem_yoneticisi','admin','yedek_parca']))<label class="report-type"><input type="radio" name="tur" value="stok" @if($rol==='yedek_parca') checked @endif><strong>Stok kontrolü</strong><small class="d-block text-muted mt-1">Kritik stok, değer ve raf uyarıları</small></label><label class="report-type"><input type="radio" name="tur" value="stok_detay"><strong>OEM / raf listesi</strong><small class="d-block text-muted mt-1">Parça, uyumluluk, raf ve fiyat ayrıntısı</small></label>@endif
  </div>
  <div class="row g-3 align-items-end">@if($firmalar->isNotEmpty())<div class="col-md-4"><label class="form-label">Firma kapsamı</label><select class="form-select" name="firma_id"><option value="">Tüm firmalar</option>@foreach($firmalar as $firma)<option value="{{ $firma->id }}">{{ $firma->unvan }}</option>@endforeach</select></div>@endif<div class="col-md-{{ $firmalar->isNotEmpty() ? '4' : '6' }}"><label class="form-label">Rapor dönemi</label><input class="form-control" type="month" name="donem" value="{{ now()->format('Y-m') }}"></div><div class="col-md-4"><button class="btn btn-warning w-100 fw-bold py-2"><i class="bi bi-bar-chart-line"></i> Ayrıntılı Raporu Oluştur</button></div></div>
 </form>
 <div class="reports-grid">@foreach($kartlar as [$baslik,$deger,$ikon])<article class="report-card"><i class="bi {{ $ikon }}"></i><span>{{ $baslik }}</span><strong>{{ is_numeric($deger) ? number_format($deger,0,',','.') : $deger }}</strong></article>@endforeach</div>
</section>
@endsection
