@extends('layouts.app')
@section('title',$baslik)
@section('content')
<style>
.report-result{max-width:1380px;margin:auto}.result-head{border-radius:22px;padding:28px;color:#fff;background:linear-gradient(120deg,#10264b,#2167c8)}.result-head p{margin:8px 0 0;color:#dceaff}.result-actions{display:flex;gap:9px;flex-wrap:wrap}.kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}.kpi{border:1px solid #dce6f3;border-radius:16px;background:#fff;padding:18px;box-shadow:0 8px 22px #0f25410d}.kpi span{color:#637694;font-size:.9rem}.kpi strong{display:block;font-size:1.5rem;color:#10264b;margin-top:8px}.kpi i{float:right;color:#d7aa15;font-size:1.35rem}.report-panel{border:1px solid #dce6f3;border-radius:18px;background:#fff;padding:20px;margin:16px 0;box-shadow:0 8px 22px #0f25410d}.chart{height:210px;display:flex;align-items:end;gap:5px;padding:15px 0 0;border-bottom:1px solid #dce6f3}.bar{flex:1;min-width:9px;background:#2c65c9;border-radius:6px 6px 0 0;position:relative}.bar small{position:absolute;bottom:-19px;left:50%;transform:translateX(-50%);font-size:9px;color:#76869c}.alerts{display:grid;gap:9px}.alert-item{padding:12px 14px;border-radius:11px}.alert-item.kritik{background:#fff0f0;color:#a22222}.alert-item.uyari{background:#fff8df;color:#795905}.alert-item.olumlu{background:#ecfdf5;color:#08734c}.table thead th{background:#eef4fb;color:#365477;white-space:nowrap}.table td{vertical-align:middle}@media(max-width:850px){.kpi-grid{grid-template-columns:repeat(2,1fr)}.result-head{padding:20px}}@page{size:A4 landscape;margin:12mm}@media print{body{background:#fff!important;font-size:10pt!important}.no-print,.sidebar,.app-sidebar,header,footer{display:none!important}.report-panel,.kpi{box-shadow:none!important;break-inside:avoid}.report-result{max-width:none}.result-head{background:#10264b!important;color:#fff!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.kpi-grid{grid-template-columns:repeat(4,1fr)}.table{font-size:8.5pt}.table thead th{background:#e8eef7!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style>
<style>
.table-responsive{width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.report-panel #reportTable{width:100%;margin:0;border-collapse:separate;border-spacing:0;font-size:.9rem}.report-panel #reportTable thead th{padding:13px 14px;background:#eef4fb;color:#365477;font-size:.72rem;font-weight:800;letter-spacing:.025em;text-transform:uppercase;white-space:nowrap;border-bottom:1px solid #cbd9e8}.report-panel #reportTable td{padding:14px;vertical-align:top;line-height:1.45;border-bottom:1px solid #e6edf5;overflow-wrap:anywhere}.report-panel #reportTable tbody tr:last-child td{border-bottom:0}.report-panel #reportTable tbody tr:hover td{background:#f8fbff}.report-tools{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:14px 0}.report-count{padding:7px 10px;border-radius:9px;background:#edf4fb;color:#365477;font-size:.76rem;font-weight:800}.report-search{position:relative;width:min(370px,100%)}.report-search i{position:absolute;left:13px;top:50%;transform:translateY(-50%);color:#73869d}.report-search input{width:100%;min-height:42px;padding:9px 12px 9px 39px;border:1px solid #ccd9e7;border-radius:10px}.tema-koyu .report-panel #reportTable thead th{background:#17243a;color:#cbd8ea}.tema-koyu .report-panel #reportTable tbody tr:hover td{background:#17243a}.tema-koyu .report-count{background:#1d304b;color:#dbeafe}@media(max-width:850px){.result-actions,.result-actions .btn{width:100%}.report-tools{align-items:stretch;flex-direction:column}.report-search{width:100%}.report-panel{padding:16px}.report-panel #reportTable,.report-panel #reportTable tbody,.report-panel #reportTable tr,.report-panel #reportTable td{display:block;width:100%}.report-panel #reportTable thead{display:none}.report-panel #reportTable tbody{display:grid;gap:12px}.report-panel #reportTable tbody tr{display:block;padding:13px 14px;border:1px solid #dce6f1;border-radius:13px;background:#fff;box-shadow:0 5px 15px rgba(15,37,65,.045)}.report-panel #reportTable td{display:grid;grid-template-columns:minmax(105px,36%) minmax(0,1fr);gap:10px;padding:8px 0!important;border-bottom:1px dashed #e0e8f1!important;text-align:left!important}.report-panel #reportTable td:last-child{border-bottom:0!important}.report-panel #reportTable td::before{content:attr(data-label);color:#6b7e96;font-size:.68rem;font-weight:800;letter-spacing:.025em;text-transform:uppercase}.tema-koyu .report-panel #reportTable tbody tr{background:#111c2e;border-color:#263652}.tema-koyu .report-panel #reportTable td{border-color:#263652!important}}@media(max-width:480px){.kpi-grid{grid-template-columns:1fr}.report-panel #reportTable td{grid-template-columns:1fr}.report-panel #reportTable td::before{margin-bottom:-5px}}
</style>
@php($para = fn($v) => '₺'.number_format((float)$v,2,',','.'))
<section class="report-result">
 <header class="result-head d-flex justify-content-between gap-3 align-items-start flex-wrap"><div><div class="text-uppercase small fw-semibold opacity-75">{{ $firmaAdi }}</div><h1 class="h3 mb-1">{{ $baslik }}</h1><p>{{ $donem->translatedFormat('F Y') }} · Oluşturma: {{ now()->format('d.m.Y H:i') }}</p></div><div class="result-actions no-print"><a class="btn btn-light" href="{{ route('raporlar.index') }}"><i class="bi bi-arrow-left"></i> Rapor Merkezi</a><button class="btn btn-warning" onclick="exportReport()"><i class="bi bi-file-earmark-spreadsheet"></i> Excel Raporu</button><button class="btn btn-outline-light" onclick="window.print()"><i class="bi bi-printer"></i> Ayrıntılı PDF</button></div></header>
 <div class="kpi-grid">@foreach($rapor['kpis'] as [$etiket,$deger,$turDeger,$ikon])<article class="kpi"><i class="bi {{ $ikon }}"></i><span>{{ $etiket }}</span><strong>{{ $turDeger==='para' ? $para($deger) : number_format((float)$deger, $turDeger==='saat'?1:0,',','.') . ($turDeger==='saat'?' saat':'') }}</strong></article>@endforeach</div>
 <section class="report-panel"><h2 class="h5">Kontrol ve uyarılar</h2><div class="alerts mt-3">@foreach($rapor['uyarilar'] as $uyari)<div class="alert-item {{ $uyari['seviye'] }}"><i class="bi bi-info-circle"></i> {{ $uyari['metin'] }}</div>@endforeach</div></section>
 @if($tur==='finans')<section class="report-panel"><div class="d-flex justify-content-between"><h2 class="h5">Günlük gelir eğilimi</h2><small class="text-muted">Seçilen ayın günlük gelir kaydı</small></div>@php($maks=max(1,collect($rapor['grafik'])->max('gelir')))<div class="chart">@foreach($rapor['grafik'] as $s)<div class="bar" title="{{ $s['etiket'] }} · {{ $para($s['gelir']) }}" style="height:{{ max(3,($s['gelir']/$maks)*100) }}%"><small>{{ $s['etiket'] }}</small></div>@endforeach</div></section>@endif
 @if(isset($rapor['durumlar']))<section class="report-panel"><h2 class="h5">Servis durum dağılımı</h2><div class="row g-2 mt-1">@foreach($rapor['durumlar'] as $durum)<div class="col-sm-4"><div class="border rounded-3 p-3"><span class="text-muted">{{ $durum->durum }}</span><strong class="d-block fs-4">{{ $durum->adet }}</strong></div></div>@endforeach</div></section>@endif
 @if(isset($rapor['kritik']) && $rapor['kritik']->isNotEmpty())<section class="report-panel"><h2 class="h5">Öncelikli kritik stoklar</h2><div class="d-flex flex-wrap gap-2 mt-3">@foreach($rapor['kritik'] as $parca)<span class="badge text-bg-warning p-2">{{ $parca->oem_no }} · {{ $parca->parca_adi }} ({{ $parca->stok_miktari }})</span>@endforeach</div></section>@endif
 <section class="report-panel"><div><h2 class="h5 mb-1">{{ $rapor['tablo']['başlık'] }}</h2><small class="text-muted">Seçilen dönemin tüm ayrıntılı kayıtları gösterilir; Excel olarak indirilebilir ve PDF biçiminde yazdırılabilir.</small></div><div class="report-tools no-print"><span class="report-count" id="reportCount">0 kayıt</span><label class="report-search"><i class="bi bi-search"></i><input id="reportSearch" type="search" placeholder="Rapor içinde ara" aria-label="Rapor içinde ara"></label></div><div class="table-responsive"><table class="table table-hover align-middle" id="reportTable"><thead><tr>@foreach($rapor['tablo']['başlıklar'] as $baslik)<th>{{ $baslik }}</th>@endforeach</tr></thead><tbody>
 @if(isset($rapor['satirlar']))
  @forelse($rapor['satirlar'] as $satir)<tr>@foreach($satir as $hucre)<td>{{ $hucre }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($rapor['tablo']['başlıklar']) }}" class="text-center text-muted py-4">Seçilen kriterlerde kayıt bulunamadı.</td></tr>@endforelse
 @elseif(isset($rapor['parcalar']))
  @forelse($rapor['parcalar'] as $p)<tr class="{{ $p->stok_miktari <= $p->minimum_stok ? 'table-warning':'' }}"><td>{{ $p->oem_no }}</td><td>{{ $p->parca_adi }}</td><td>{{ $p->marka ?: '—' }}</td><td>{{ $p->uyumluluk ?: '—' }}</td><td>{{ $p->raf_yeri ?: 'Adreslenmemiş' }}</td><td>{{ $p->stok_miktari }}</td><td>{{ $p->minimum_stok }}</td><td>{{ $para($p->alis_fiyati) }}</td><td>{{ $para($p->satis_fiyati) }}</td></tr>@empty<tr><td colspan="9" class="text-center text-muted py-4">Kayıt bulunamadı.</td></tr>@endforelse
 @elseif(isset($rapor['personeller']))
  @forelse($rapor['personeller'] as $p)<tr><td>{{ $p->name }}</td><td>{{ $p->email }}</td><td>{{ $p->role }}</td><td>{{ $p->unvan ?: '—' }}</td><td>{{ $para($p->net_ucret) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Aktif personel yok.</td></tr>@endforelse
 @elseif($tur==='cari')
  @forelse($rapor['cariler'] as $c)<tr><td>{{ $c->unvan }}</td><td>{{ $c->tip }}</td><td>{{ $c->telefon ?: '—' }}</td><td class="fw-bold">{{ $para($c->bakiye) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Cari kayıt yok.</td></tr>@endforelse
 @elseif($tur==='servis')
  @forelse($rapor['kayitlar'] as $s)<tr><td>{{ $s->servis_no }}</td><td>{{ \Carbon\Carbon::parse($s->servis_tarihi)->format('d.m.Y') }}</td><td>{{ $s->plaka }}</td><td>{{ $s->ad_soyad }}</td><td><span class="badge text-bg-light">{{ $s->durum }}</span></td><td>{{ $para($s->iscilik_tutari) }}</td><td>{{ $para($s->parca_tutari) }}</td><td class="fw-bold">{{ $para($s->toplam_tutar) }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Seçilen dönemde servis kaydı yok.</td></tr>@endforelse
 @else
  @forelse($rapor['kayitlar'] as $k)<tr><td>{{ $k->fis_no }}</td><td>{{ \Carbon\Carbon::parse($k->fis_tarihi)->format('d.m.Y') }}</td><td>{{ $k->cari ?: '—' }}</td><td>{{ $k->aciklama ?: '—' }}</td><td>{{ ucfirst($k->yon) }}</td><td class="fw-bold">{{ $para($k->tutar) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Seçilen dönemde mali hareket yok.</td></tr>@endforelse
 @endif
 </tbody></table></div></section>
 @if(isset($rapor['karsilastirma']))<section class="report-panel"><h2 class="h5">Önceki dönem karşılaştırması</h2><div class="row g-2 mt-2">@foreach($rapor['karsilastirma'] as $satir)<div class="col-md-6"><div class="border rounded-3 p-3"><span class="text-muted">{{ $satir[0] }}</span><strong class="d-block">{{ $para($satir[1]) }}</strong></div></div>@endforeach</div></section>@endif
</section>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const table=document.getElementById('reportTable'); if(!table)return;
 const headers=[...table.querySelectorAll('thead th')].map(th=>th.textContent.trim());
 const rows=[...table.querySelectorAll('tbody tr')];
 rows.forEach(row=>[...row.cells].forEach((cell,index)=>cell.dataset.label=headers[index]||'Detay'));
 const search=document.getElementById('reportSearch'),count=document.getElementById('reportCount');
 const update=()=>{const query=(search?.value||'').toLocaleLowerCase('tr-TR').trim();let visible=0;rows.forEach(row=>{const show=!query||row.textContent.toLocaleLowerCase('tr-TR').includes(query);row.hidden=!show;if(show)visible++});if(count)count.textContent=`${visible} kayıt`};
 search?.addEventListener('input',update);update();
});
function exportReport(){
 const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
 const kpis=[...document.querySelectorAll('.kpi')].map(k=>`<td><small>${esc(k.querySelector('span').innerText)}</small><br><b>${esc(k.querySelector('strong').innerText)}</b></td>`).join('');
 const alerts=[...document.querySelectorAll('.alert-item')].map(a=>`<li>${esc(a.innerText)}</li>`).join('');
 const table=document.getElementById('reportTable').outerHTML;
 const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;color:#172b4d;padding:24px}h1{color:#10264b;margin-bottom:4px}p{color:#526785}table{border-collapse:collapse;width:100%;margin:16px 0}th{background:#10264b;color:#fff}td,th{border:1px solid #cbd7e6;padding:9px;text-align:left}td b{font-size:15px;color:#10264b}small{color:#526785}ul{background:#fff7dc;border:1px solid #ecd486;padding:14px 28px}</style></head><body><h1>${esc(@json($baslik))}</h1><p>${esc(@json($firmaAdi))} · ${esc(@json($donem->translatedFormat('F Y')))}</p><h2>Yönetici Özeti</h2><table><tr>${kpis}</tr></table><h2>Kontrol ve Uyarılar</h2><ul>${alerts}</ul><h2>${esc(document.querySelector('#reportTable').closest('.report-panel').querySelector('h2').innerText)}</h2>${table}</body></html>`;
 const blob=new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='{{ \Illuminate\Support\Str::slug($baslik) }}-{{ $donem->format('Y-m') }}.xls';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);
}
</script>
@endsection
