@extends('layouts.app')
@section('title', $modul==='randevu'?'Randevu ve Ajanda':($modul==='sigorta'?'Sigorta / Kasko':'B2B Siparişleri'))
@section('content')
<section class="container" style="max-width:1350px"><header class="p-4 rounded-4 text-white mb-3" style="background:linear-gradient(115deg,#102a50,#0f766e)"><h1 class="h3 mb-1">@if($modul==='randevu')<i class="bi bi-calendar-week"></i> Randevu ve Servis Ajandası @elseif($modul==='sigorta')<i class="bi bi-shield-check"></i> Sigorta / Kasko Hasar Takibi @else<i class="bi bi-cart-check"></i> B2B Sipariş Merkezi @endif</h1><p class="mb-0">Firma ve şube kapsamlı kayıtlar; ilgili müşteri, araç ve operasyon süreciyle birlikte izlenir.</p></header>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3"><div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5">@if($modul==='randevu')Yeni randevu @elseif($modul==='sigorta')Yeni hasar dosyası @else>Yeni B2B siparişi @endif</h2>
@if($modul==='randevu')<form method="post" action="{{route('operasyon.randevular.kaydet')}}">@csrf @include('operasyon.partials.iliskiler')<label>Hizmet türü</label><select name="hizmet_turu"><option>Periyodik Bakım</option><option>Yağ Değişimi</option><option>Mekanik Onarım</option><option>Elektrik ve Elektronik</option><option>Kaporta / Boya</option><option>Lastik / Rot Balans</option></select><label>Başlangıç</label><input type="datetime-local" name="baslangic" value="{{now()->format('Y-m-d\\TH:i')}}" required><label>Durum</label><select name="durum"><option value="planlandi">Planlandı</option><option value="teyitli">Teyitli</option><option value="iptal">İptal</option><option value="tamamlandi">Tamamlandı</option></select><label>Notlar</label><textarea name="notlar"></textarea><button class="btn btn-primary mt-3">Ajandaya Ekle</button></form>
@elseif($modul==='sigorta')<form method="post" action="{{route('operasyon.sigorta.kaydet')}}">@csrf @include('operasyon.partials.iliskiler')<label>Hasar dosya no</label><input name="dosya_no" required><label>Sigorta firması</label><select name="sigorta_firmasi_id"><option value="">Seçiniz</option>@foreach($sigortalar as $s)<option value="{{$s->id}}">{{$s->unvan}}</option>@endforeach</select><label>Durum</label><select name="durum"><option value="acik">Açık</option><option value="ekspertiz">Ekspertiz</option><option value="onaylandi">Onaylandı</option><option value="odendi">Ödendi</option><option value="kapandi">Kapandı</option></select><label>Onaylı tutar</label><input type="number" step=".01" name="onayli_tutar" value="0"><label>Açıklama</label><textarea name="aciklama"></textarea><button class="btn btn-primary mt-3">Hasar Dosyası Aç</button></form>
@else<form method="post" action="{{route('operasyon.b2b.kaydet')}}">@csrf<label>Alıcı firma / bayi</label><input name="alici_unvan" required><label>Stok ürünü</label><select name="stok_parca_id"><option value="">Serbest ürün satırı</option>@foreach($parcalar as $p)<option value="{{$p->id}}">{{$p->parca_adi}} · {{$p->oem_no}}</option>@endforeach</select><label>Ürün adı</label><input name="urun_adi" required><div class="row"><div class="col"><label>Miktar</label><input type="number" step=".01" name="miktar" required></div><div class="col"><label>Birim fiyat</label><input type="number" step=".01" name="birim_fiyat" required></div></div><label>Durum</label><select name="durum"><option value="taslak">Taslak</option><option value="onaylandi">Onaylandı</option><option value="hazirlaniyor">Hazırlanıyor</option><option value="kargoda">Kargoda</option><option value="tamamlandi">Tamamlandı</option><option value="iptal">İptal</option></select><button class="btn btn-primary mt-3">Siparişi Kaydet</button></form>@endif</div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body table-responsive"><h2 class="h5">Kayıtlar</h2><table class="table align-middle"><thead><tr>@if($modul==='randevu')<th>Tarih</th><th>Müşteri / Araç</th><th>Hizmet</th><th>Durum</th>@elseif($modul==='sigorta')<th>Dosya</th><th>Sigorta / Araç</th><th>Tutar</th><th>Durum</th>@else<th>Sipariş no</th><th>Alıcı</th><th>Tutar</th><th>Durum</th>@endif</tr></thead><tbody>@forelse($kayitlar as $k)<tr>@if($modul==='randevu')<td>{{\Carbon\Carbon::parse($k->baslangic)->format('d.m.Y H:i')}}</td><td>{{$k->ad_soyad ?: '-'}}<small class="d-block">{{$k->plaka ?: '-'}}</small></td><td>{{$k->hizmet_turu}}</td><td>{{$k->durum}}</td>@elseif($modul==='sigorta')<td>{{$k->dosya_no}}</td><td>{{$k->sigorta_unvan ?: 'Firma seçilmedi'}}<small class="d-block">{{$k->plaka ?: '-'}}</small></td><td>₺{{number_format($k->onayli_tutar,2,',','.')}}</td><td>{{$k->durum}}</td>@else<td>{{$k->siparis_no}}</td><td>{{$k->alici_unvan}}</td><td>₺{{number_format($k->toplam_tutar,2,',','.')}}</td><td>{{$k->durum}}</td>@endif</tr>@empty<tr><td colspan="4" class="text-muted">Henüz kayıt yok.</td></tr>@endforelse</tbody></table></div></div></div></div></section>
@endsection
