@extends('layouts.app')

@section('title', 'Firma Kartı')

@section('content')
<style>
    .firma-detail{max-width:1180px;margin:0 auto}.firma-detail *{box-sizing:border-box}.firma-detail__head h1{margin:0;color:#17233c;font-size:27px;font-weight:800}.firma-detail__head h1 i{color:#2563eb;margin-right:8px}.firma-detail__head p{margin:7px 0 0;color:#64748b;font-size:14px}.firma-detail__actions{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin:22px 0}.firma-detail__button{min-height:43px;padding:10px 12px;border-radius:10px;display:flex;align-items:center;justify-content:center;gap:7px;text-decoration:none;font-size:13px;font-weight:800;white-space:nowrap}.firma-detail__back{background:#dbeafe;color:#1d4ed8}.firma-detail__neutral{background:#e2e8f0;color:#334155}.firma-detail__edit{background:#fef3c7;color:#92400e}.firma-detail__branch{background:#ede9fe;color:#6d28d9}.firma-detail__card{padding:25px;background:#fff;border:1px solid #e5eaf1;border-radius:19px;box-shadow:0 7px 22px rgba(15,23,42,.06)}.firma-detail__card h2{margin:0 0 21px;padding-bottom:16px;border-bottom:1px solid #edf1f5;color:#1e293b;font-size:19px}.firma-detail__card h2 i{color:#2563eb;margin-right:7px}.firma-detail__grid{margin:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.firma-detail__grid div{min-width:0;padding:15px 16px;border:1px solid #e1e8f0;border-radius:12px;background:#f8fafc}.firma-detail__grid dt{margin:0 0 5px;color:#718096;font-size:12px;font-weight:700}.firma-detail__grid dd{margin:0;color:#263449;font-size:15px;font-weight:750;line-height:1.45;overflow-wrap:anywhere}.firma-detail__full{grid-column:1/-1}.firma-detail__status{display:inline-flex;padding:4px 9px;border-radius:999px;font-size:12px;font-weight:800}.firma-detail__status--active{background:#dcfce7;color:#15803d}.firma-detail__status--passive{background:#fee2e2;color:#b91c1c}@media(max-width:760px){.firma-detail__actions{grid-template-columns:repeat(2,minmax(0,1fr))}.firma-detail__grid{grid-template-columns:1fr}.firma-detail__full{grid-column:auto}}@media(max-width:430px){.firma-detail__actions{grid-template-columns:1fr}.firma-detail__card{padding:18px}}
</style>
<section class="firma-detail">
    <header class="firma-detail__head"><h1><i class="bi bi-building"></i> {{ $firma->unvan }}</h1><p>Firma kartı ve bağlı yapı özeti.</p></header>
    @if(session('success'))<div class="alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert-danger">{{ session('error') }}</div>@endif
    <nav class="firma-detail__actions"><a href="{{ route('firma.index') }}" class="firma-detail__button firma-detail__back"><i class="bi bi-arrow-left"></i> Firma Listesine Dön</a><a href="{{ auth()->user()->tamSistemYetkisiVarMi() ? route('ayarlar.index') : route('dashboard') }}" class="firma-detail__button firma-detail__neutral"><i class="bi bi-gear"></i> {{ auth()->user()->tamSistemYetkisiVarMi() ? 'Ayarlara Dön' : 'Panele Dön' }}</a><a href="{{ route('firma.edit', $firma) }}" class="firma-detail__button firma-detail__edit"><i class="bi bi-pencil"></i> Düzenle</a><a href="{{ route('sube.index', $firma) }}" class="firma-detail__button firma-detail__branch"><i class="bi bi-diagram-3"></i> Şubeler</a></nav>
    <article class="firma-detail__card"><h2><i class="bi bi-info-circle"></i> Firma Bilgileri</h2><dl class="firma-detail__grid"><div><dt>Firma Ünvanı</dt><dd>{{ $firma->unvan }}</dd></div><div><dt>Vergi No</dt><dd>{{ $firma->vergi_no ?: '-' }}</dd></div><div><dt>Telefon</dt><dd>{{ $firma->telefon ?: '-' }}</dd></div><div><dt>E-posta</dt><dd>{{ $firma->email ?: '-' }}</dd></div><div><dt>Şube Sayısı</dt><dd>{{ $firma->subeler_count }}</dd></div><div><dt>Personel Sayısı</dt><dd>{{ $firma->personeller_count }}</dd></div><div><dt>Durum</dt><dd><span class="firma-detail__status {{ $firma->aktif ? 'firma-detail__status--active' : 'firma-detail__status--passive' }}">{{ $firma->aktif ? 'Aktif' : 'Pasif' }}</span></dd></div><div><dt>Merkez Gösterimi</dt><dd>{{ $firma->merkez_goster ? 'Açık' : 'Kapalı' }}</dd></div><div class="firma-detail__full"><dt>Adres</dt><dd>{{ $firma->adres ?: '-' }}</dd></div></dl></article>
</section>
@endsection
