@extends('layouts.app')

@section('title', $tur === 'teklif' ? 'Teklifler' : 'Faturalar')

@section('content')
@php($isTeklif = $tur === 'teklif')
<style>
.doc{max-width:1440px;margin:auto}.doc-hero{padding:25px;border-radius:20px;background:linear-gradient(110deg,#102a50,#1d5a70);color:#fff}.doc-hero p{margin:7px 0 0;color:#d9eaff}.doc-nav{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.doc-nav a{padding:9px 12px;text-decoration:none;border-radius:10px;background:#ffffff22;color:#fff;font-weight:700}.doc-nav a.active{background:#f1c94d;color:#11284d}.doc-card{margin-top:16px;padding:18px;background:#fff;border:1px solid #dce6ef;border-radius:16px}.doc-form-grid{display:grid;grid-template-columns:1.1fr 1fr 165px 165px 130px;gap:12px}.doc-form-grid label{font-size:12px;color:#3e5573;font-weight:800;display:block;margin-bottom:5px}.doc-lines{width:100%;min-width:940px;border-collapse:collapse}.doc-lines th{background:#eff5fa;color:#506681;padding:11px;text-align:left;font-size:12px}.doc-lines td{padding:7px;border-bottom:1px solid #e7edf4}.doc-lines input,.doc-lines select{margin:0;min-height:38px;padding:7px}.doc-total{display:flex;justify-content:flex-end;gap:22px;flex-wrap:wrap;margin-top:15px;padding:14px;background:#fff7d9;border-radius:11px;font-weight:700}.doc-total strong{font-size:20px;color:#11284d}.doc-actions{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-top:15px}.doc-list{width:100%;border-collapse:collapse;min-width:860px}.doc-list th{padding:12px;background:#eff5fa;font-size:12px;color:#506681;text-align:left}.doc-list td{padding:13px;border-bottom:1px solid #e7edf4}.doc-status{padding:5px 9px;border-radius:999px;background:#fff3c7;color:#735900;font-size:11px;font-weight:800}.doc-status.sent{background:#dceaff;color:#1b5aa4}.doc-status.done{background:#dff5e7;color:#177443}@media(max-width:1000px){.doc-form-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.doc-hero{padding:20px}.doc-form-grid{grid-template-columns:1fr 1fr}.doc-actions{align-items:stretch;flex-direction:column}.doc-actions .btn{width:100%}}@media(max-width:420px){.doc-form-grid{grid-template-columns:1fr}}
</style>
<section class="doc">
    <header class="doc-hero"><div class="small fw-bold text-warning">SATIŞ BELGELERİ</div><h1 class="h3 mb-0">{{ $isTeklif ? 'Teklif Yönetimi' : 'Fatura Yönetimi' }}</h1><p>{{ $isTeklif ? 'Teklif hazırlayın, geçerlilik tarihini takip edin ve müşteri onayına hazır taslak oluşturun.' : 'Fatura taslağını satır bazlı KDV, vade ve entegrasyon durumuyla yönetin.' }}</p>@include('components.muhasebe-menu', ['firmaId' => $firmaId])</header>
    @if(session('success'))<div class="alert alert-success mt-3">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger mt-3">{{ $errors->first() }}</div>@endif
    <article class="doc-card"><h2 class="h5">Yeni {{ $isTeklif ? 'teklif' : 'fatura taslağı' }}</h2>
        <form method="POST" action="{{ route('ticari.belge.kaydet', $tur) }}" id="belge-form">@csrf
            <div class="doc-form-grid"><div><label>Firma</label><input value="{{ $firmalar->firstWhere('id', $firmaId)?->gosterim_adi }}" disabled></div><div><label>Cari kart</label><select id="cari-select" name="cari_hesap_id"><option value="">Cari seçilmedi</option>@foreach($cariler as $cari)<option value="{{ $cari->id }}" data-unvan="{{ $cari->unvan }}">{{ $cari->unvan }} · {{ $cari->tip === 'musteri' ? 'Müşteri' : 'Tedarikçi' }}</option>@endforeach</select></div><div><label>{{ $isTeklif ? 'Teklif tarihi' : 'Fatura tarihi' }}</label><input type="date" name="tarih" value="{{ now()->format('Y-m-d') }}" required></div><div><label>{{ $isTeklif ? 'Geçerlilik tarihi' : 'Vade tarihi' }}</label><input type="date" name="{{ $isTeklif ? 'gecerlilik_tarihi' : 'vade_tarihi' }}" value="{{ $isTeklif ? now()->addDays(15)->format('Y-m-d') : now()->format('Y-m-d') }}"></div><div><label>Para birimi</label><select name="para_birimi"><option value="TRY">TRY ₺</option><option value="USD">USD $</option><option value="EUR">EUR €</option></select></div><div style="grid-column:1/-1"><label>Müşteri / firma ünvanı</label><input id="musteri-unvan" name="musteri_unvan" required placeholder="Cari karttan seçin veya ünvanı yazın"></div></div>
            <div class="table-responsive mt-4"><table class="doc-lines"><thead><tr><th>Ürün / hizmet</th><th>Miktar</th><th>Birim</th><th>Birim fiyat</th><th>İskonto %</th><th>KDV</th><th>Toplam</th><th></th></tr></thead><tbody id="satirlar"><tr class="doc-line"><td><input name="satirlar[0][urun_hizmet_adi]" required placeholder="İşçilik, parça veya hizmet"></td><td><input class="miktar" type="number" min="0.001" step="0.001" value="1" name="satirlar[0][miktar]" required></td><td><select name="satirlar[0][birim]"><option>Adet</option><option>Saat</option><option>Hizmet</option><option>Kg</option></select></td><td><input class="fiyat" type="number" min="0" step=".01" name="satirlar[0][birim_fiyat]" required></td><td><input class="iskonto" type="number" min="0" max="100" step=".01" value="0" name="satirlar[0][iskonto_orani]"></td><td><select class="kdv" name="satirlar[0][kdv_orani]"><option value="1">%1</option><option value="5">%5</option><option value="8">%8</option><option value="10">%10</option><option value="20" selected>%20</option></select></td><td class="line-total">₺0,00</td><td><button type="button" class="btn btn-sm btn-outline-danger satir-sil" aria-label="Satırı sil"><i class="bi bi-trash3"></i></button></td></tr></tbody></table></div>
            <div class="doc-total"><span>Ara toplam: <b id="ara-toplam">₺0,00</b></span><span>KDV: <b id="kdv-toplam">₺0,00</b></span><span>Genel toplam: <strong id="genel-toplam">₺0,00</strong></span></div><div class="doc-actions"><button type="button" id="satir-ekle" class="btn btn-outline-secondary"><i class="bi bi-plus-lg"></i> Satır Ekle</button><button class="btn btn-primary"><i class="bi bi-check2-circle"></i> {{ $isTeklif ? 'Teklif Taslağını Oluştur' : 'Fatura Taslağını Oluştur' }}</button></div><label class="mt-3">Notlar</label><textarea name="notlar" rows="3" placeholder="Teslim, ödeme veya belge notu"></textarea>
        </form>
    </article>
    <article class="doc-card"><div class="d-flex justify-content-between align-items-center"><h2 class="h5 mb-0">{{ $isTeklif ? 'Teklif listesi' : 'Fatura listesi' }}</h2><span class="text-muted small">{{ $kayitlar->count() }} kayıt</span></div><div class="table-responsive mt-3"><table class="doc-list"><thead><tr><th>{{ $isTeklif ? 'Teklif no' : 'Fatura no' }}</th><th>Müşteri</th><th>Tarih</th><th>{{ $isTeklif ? 'Geçerlilik' : 'Vade' }}</th><th>Durum</th><th class="text-end">Toplam</th><th>Çıktı</th></tr></thead><tbody>@forelse($kayitlar as $kayit)<tr><td><strong>{{ $isTeklif ? $kayit->teklif_no : $kayit->fatura_no }}</strong><br><small class="text-muted">{{ $kayit->para_birimi ?? 'TRY' }}</small></td><td>{{ $kayit->musteri_unvan }}@if($kayit->cari_plaka)<br><small class="text-muted">{{ $kayit->cari_plaka }}</small>@endif</td><td>{{ \Carbon\Carbon::parse($kayit->tarih)->format('d.m.Y') }}</td><td>{{ ($isTeklif ? $kayit->gecerlilik_tarihi : $kayit->vade_tarihi) ? \Carbon\Carbon::parse($isTeklif ? $kayit->gecerlilik_tarihi : $kayit->vade_tarihi)->format('d.m.Y') : '—' }}</td><td><span class="doc-status {{ in_array($kayit->durum, ['onaylandi','odendi']) ? 'done' : ($kayit->durum === 'gonderildi' ? 'sent' : '') }}">{{ ucfirst($kayit->durum) }}</span>@if(!$isTeklif)<br><small class="text-muted">{{ $kayit->entegrasyon_durumu }}</small>@endif</td><td class="text-end fw-bold">₺ {{ number_format($kayit->tutar,2,',','.') }}</td><td><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ route('ciktilar.yazdir',['tur'=>$tur,'id'=>$kayit->id]) }}">PDF</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('ciktilar.excel',['tur'=>$tur,'id'=>$kayit->id]) }}">Excel</a></div></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5">Henüz belge yok. İlk belgeyi yukarıdaki formdan oluşturabilirsiniz.</td></tr>@endforelse</tbody></table></div></article>
</section>
<script>document.addEventListener('DOMContentLoaded',()=>{const box=document.getElementById('satirlar'),money=n=>'₺'+Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});let index=1;const calc=()=>{let ara=0,kdv=0;box.querySelectorAll('.doc-line').forEach(row=>{const miktar=+row.querySelector('.miktar').value||0,fiyat=+row.querySelector('.fiyat').value||0,iskonto=+row.querySelector('.iskonto').value||0,oran=+row.querySelector('.kdv').value||0,net=miktar*fiyat*(1-iskonto/100),vergi=net*oran/100;ara+=net;kdv+=vergi;row.querySelector('.line-total').textContent=money(net+vergi)});document.getElementById('ara-toplam').textContent=money(ara);document.getElementById('kdv-toplam').textContent=money(kdv);document.getElementById('genel-toplam').textContent=money(ara+kdv)};const bind=row=>{row.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',calc));row.querySelector('.satir-sil').addEventListener('click',()=>{if(box.children.length>1){row.remove();calc()}})};bind(box.firstElementChild);document.getElementById('satir-ekle').addEventListener('click',()=>{const row=box.firstElementChild.cloneNode(true);row.querySelectorAll('input,select').forEach(el=>{el.name=el.name.replace(/\[\d+\]/,'['+index+']');if(el.classList.contains('miktar'))el.value=1;else if(el.classList.contains('iskonto'))el.value=0;else if(el.tagName==='SELECT')el.selectedIndex=0;else el.value=''});row.querySelector('.line-total').textContent='₺0,00';box.appendChild(row);bind(row);row.querySelector('input[name$="[urun_hizmet_adi]"]')?.focus();index++});document.getElementById('cari-select').addEventListener('change',event=>{const option=event.target.selectedOptions[0];if(option?.dataset.unvan)document.getElementById('musteri-unvan').value=option.dataset.unvan});calc()})</script>
@endsection
