@extends('layouts.app')
@section('title','Cari Hesaplar')
@section('content')
<style>
.cari{max-width:1440px;margin:auto}.cari-head{padding:25px;border-radius:20px;background:linear-gradient(110deg,#102a50,#1d5a70);color:#fff}.cari-head p{color:#d9eaff;margin:7px 0 0}.cari-tools,.cari-panel{margin-top:16px;padding:16px;background:#fff;border:1px solid #dce6ef;border-radius:16px}.cari-tools{display:flex;gap:11px;align-items:end;flex-wrap:wrap}.cari-tools>div{min-width:180px}.cari-tools .search{flex:1;min-width:250px}.cari-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin-top:16px}.cari-stat{background:#fff;border:1px solid #dce6ef;border-radius:15px;padding:16px}.cari-stat span{font-size:12px;color:#63748b;font-weight:700}.cari-stat strong{font-size:22px;display:block;margin-top:7px;color:#11284d}.cari-main{display:grid;grid-template-columns:360px 1fr;gap:16px;margin-top:16px}.cari-main label{font-weight:700;font-size:13px;color:#344c6e}.cari-main input,.cari-main select{margin:5px 0 11px}.cari-table{width:100%;border-collapse:collapse;min-width:800px}.cari-table th{padding:12px;text-align:left;background:#eff5fa;color:#506681;font-size:12px}.cari-table td{padding:13px 12px;border-bottom:1px solid #e9eff5}.cari-tag{font-size:11px;font-weight:800;border-radius:999px;padding:4px 8px;background:#e8f0fb;color:#204f87}.cari-balance.pos{color:#197343}.cari-balance.neg{color:#c13e4a}@media(max-width:950px){.cari-main{grid-template-columns:1fr}.cari-stats{grid-template-columns:1fr 1fr}}@media(max-width:550px){.cari-head{padding:20px}.cari-stats{grid-template-columns:1fr}.cari-tools>div,.cari-tools .search{width:100%}}
</style>
<section class="cari"><header class="cari-head"><div class="d-flex justify-content-between gap-3 flex-wrap"><div><div class="small fw-bold text-warning">CARİ YÖNETİMİ</div><h1 class="h3 mb-0">Cari Hesaplar</h1><p>Müşteri, tedarikçi ve diğer cari kartları; bakiye ve iletişim bilgileri ile yönetin.</p></div><a href="{{ route('ticari.index',['firma_id'=>$firmaId]) }}" class="btn btn-light align-self-start">Muhasebe Merkezi</a></div>@include('components.muhasebe-menu',['firmaId'=>$firmaId])</header>@if(session('success'))<div class="alert alert-success mt-3">{{ session('success') }}</div>@endif
<form class="cari-tools" method="GET"><input type="hidden" name="firma_id" value="{{ $firmaId }}"><div><label class="form-label">Firma</label><select onchange="this.form.submit()" name="firma_id">@foreach($firmalar as $firma)<option value="{{ $firma->id }}" @selected($firmaId==$firma->id)>{{ $firma->gosterim_adi }}</option>@endforeach</select></div><div class="search"><label class="form-label">Cari ara</label><input name="ara" value="{{ $arama }}" placeholder="Ünvan, plaka, vergi no veya telefon"></div><div><label class="form-label">Cari türü</label><select name="tip"><option value="">Tüm cari türleri</option><option value="musteri" @selected($tip==='musteri')>Müşteri</option><option value="tedarikci" @selected($tip==='tedarikci')>Tedarikçi</option><option value="diger" @selected($tip==='diger')>Diğer</option></select></div><button class="btn btn-primary"><i class="bi bi-search"></i> Listele</button><a class="btn btn-outline-secondary" href="{{ route('ticari.cari',['firma_id'=>$firmaId]) }}">Temizle</a></form>
<div class="cari-stats"><article class="cari-stat"><span>Aktif cari kart</span><strong>{{ $cariOzet['aktif'] }}</strong></article><article class="cari-stat"><span>Toplam alacak</span><strong class="text-success">₺ {{ number_format($cariOzet['alacak'],2,',','.') }}</strong></article><article class="cari-stat"><span>Toplam borç</span><strong class="text-danger">₺ {{ number_format($cariOzet['borc'],2,',','.') }}</strong></article></div>
<div class="cari-main"><article class="cari-panel"><h2 class="h5">Yeni cari kart</h2><p class="small text-muted">Cari kart, teklif, fatura ve fiş ekranlarından seçilebilir.</p><form method="POST" action="{{ route('ticari.cari.kaydet') }}">@csrf<label>Tür</label><select name="tip"><option value="musteri">Müşteri</option><option value="tedarikci">Tedarikçi</option><option value="diger">Diğer</option></select><label>Ünvan / ad soyad</label><input name="unvan" required placeholder="Cari ünvanı"><label>Plaka</label><input name="plaka" placeholder="34 ABC 123"><label>Telefon</label><input name="telefon" placeholder="05xx xxx xx xx"><label>E-posta</label><input type="email" name="email" placeholder="ornek@firma.com"><label>Vergi no / T.C.</label><input name="vergi_no"><button class="btn btn-primary w-100 mt-2"><i class="bi bi-plus-lg"></i> Cari Kartı Kaydet</button></form></article><article class="cari-panel"><div class="d-flex justify-content-between align-items-center"><h2 class="h5 mb-0">Cari kart listesi</h2><span class="small text-muted">{{ $cariler->count() }} kayıt</span></div><div class="table-responsive mt-3"><table class="cari-table"><thead><tr><th>Cari</th><th>Tür</th><th>Plaka</th><th>Vergi no</th><th>İletişim</th><th class="text-end">Bakiye</th></tr></thead><tbody>@forelse($cariler as $cari)<tr><td><strong>{{ $cari->unvan }}</strong><br><small class="text-muted">{{ $cari->aktif?'Aktif':'Pasif' }}</small></td><td><span class="cari-tag">{{ $cari->tip==='musteri'?'Müşteri':($cari->tip==='tedarikci'?'Tedarikçi':'Diğer') }}</span></td><td>{{ $cari->plaka ?: '—' }}</td><td>{{ $cari->vergi_no ?: '—' }}</td><td>{{ $cari->telefon ?: '—' }}<br><small>{{ $cari->email ?: '' }}</small></td><td class="text-end fw-bold cari-balance {{ (float)$cari->bakiye<0?'neg':'pos' }}">₺ {{ number_format(abs((float)$cari->bakiye),2,',','.') }}<br><small>{{ (float)$cari->bakiye<0?'Borç':'Alacak' }}</small></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">Seçili filtrelerde cari kart bulunamadı.</td></tr>@endforelse</tbody></table></div></article></div></section>
@endsection
