@extends('layouts.app')
@section('title','Yeni Araç | İZGİOS')
@section('content')
<section class="container py-4 servis-form"><div class="servis-form-hero"><div><div class="eyebrow">SERVİS AKIŞI · 2. ADIM</div><h1>Araç Kaydı</h1><p>Müşteriye bağlı araç kartını oluşturun; kaydın ardından servis kabul ekranı açılır.</p></div><i class="bi bi-car-front"></i></div>
@include('components.servis-akisi', ['aktifAdim' => 2])
<form action="{{ route('araclar.store') }}" method="POST" class="card corporate-form">@csrf
<div class="card-body p-4 p-lg-5"><div class="form-section-title"><i class="bi bi-person-check"></i><div><h2>Araç sahibi</h2><p>Bu araç hangi müşteri kartına bağlanacak?</p></div></div><div class="row g-3"><div class="col-12"><label>Müşteri <sup>*</sup></label><select name="musteri_id" required><option value="">Müşteri seçiniz</option>@foreach($musteriler as $musteri)<option value="{{ $musteri->id }}" @selected(old('musteri_id', $seciliMusteriId ?? null) == $musteri->id)>{{ $musteri->ad_soyad }} · {{ $musteri->telefon }}</option>@endforeach</select></div></div><hr class="my-4"><div class="form-section-title"><i class="bi bi-car-front-fill"></i><div><h2>Araç bilgileri</h2><p>Plaka ve temel teknik bilgiler araç kartında saklanır.</p></div></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-3"><div class="col-md-6"><label>Plaka <sup>*</sup></label><input name="plaka" value="{{ old('plaka') }}" required placeholder="34 ABC 123" style="text-transform:uppercase"></div><div class="col-md-6"><label>Model Yılı</label><input type="number" name="model_yili" value="{{ old('model_yili') }}" min="1900" max="2100" placeholder="Örn: 2024"></div><div class="col-md-6"><label>Marka <sup>*</sup></label><select name="marka" id="marka" required><option value="">Marka seçiniz</option></select></div><div class="col-md-6"><label>Model <sup>*</sup></label><select name="model" id="model" required><option value="">Önce marka seçiniz</option></select></div><div class="col-md-4"><label>Mevcut Kilometre</label><input type="number" name="kilometre" value="{{ old('kilometre') }}" min="0" placeholder="Örn: 125000"></div><div class="col-md-4"><label>Yakıt Tipi</label><select name="yakit_tipi"><option value="">Seçiniz</option><option>Benzin</option><option>Dizel</option><option>LPG</option><option>Hibrit</option><option>Elektrik</option></select></div><div class="col-md-4"><label>Vites</label><select name="vites"><option value="">Seçiniz</option><option>Manuel</option><option>Otomatik</option><option>Yarı Otomatik</option></select></div><div class="col-md-6"><label>Şasi No</label><input name="sase_no" value="{{ old('sase_no') }}" placeholder="Opsiyonel"></div><div class="col-md-6"><label>Motor No</label><input name="motor_no" value="{{ old('motor_no') }}" placeholder="Opsiyonel"></div><div class="col-12"><label>Araç Notları</label><textarea name="notlar" rows="3" placeholder="Araçla ilgili kalıcı notlar">{{ old('notlar') }}</textarea></div></div></div>
<div class="form-footer"><a class="btn btn-light" href="{{ route('musteriler.index') }}"><i class="bi bi-arrow-left"></i> Müşterilere Dön</a><button class="btn btn-primary" type="submit">Araç Kaydet ve Servis Kabule Geç <i class="bi bi-arrow-right"></i></button></div></form></section>
@include('components.servis-form-style')
<script src="{{ asset('js/arac-modelleri.js') }}"></script><script>document.addEventListener('DOMContentLoaded',()=>{const marka=document.getElementById('marka'),model=document.getElementById('model'),oncekiMarka=@json(old('marka')),oncekiModel=@json(old('model'));Object.keys(window.aracModelleri||{}).forEach(x=>marka.add(new Option(x,x)));if(oncekiMarka)marka.value=oncekiMarka;const modelleriYukle=()=>{model.innerHTML='<option value="">Model seçiniz</option>';(window.aracModelleri?.[marka.value]||[]).forEach(x=>model.add(new Option(x,x)));if(oncekiModel)model.value=oncekiModel};marka.addEventListener('change',modelleriYukle);if(marka.value)modelleriYukle();});</script>
@endsection
