@extends('layouts.app')
@section('title', 'Sistem Hataları')
@section('content')
<style>.error-center{max-width:1240px;margin:auto}.error-tools{display:flex;align-items:center;gap:12px;margin:0 0 16px;padding:14px;border:1px solid #fde68a;border-radius:12px;background:#fffbeb;color:#854d0e}.error-tools small{color:#64748b}.error-list{display:grid;gap:11px}.error-card{padding:18px 20px;border:1px solid #e6eaf0;border-left:4px solid #ef4444;border-radius:13px;background:#fff;box-shadow:0 4px 14px rgba(15,23,42,.04)}.error-card__head{display:flex;justify-content:space-between;gap:15px}.error-code{display:inline-block;padding:5px 8px;border-radius:999px;background:#fee2e2;color:#b91c1c;font-size:10px;font-weight:800}.error-card h2{margin:9px 0 0;color:#1e293b;font-size:16px}.error-time{color:#64748b;font-size:12px}.error-detail{display:grid;grid-template-columns:160px 1fr;gap:10px;margin-top:15px;padding-top:14px;border-top:1px solid #edf1f5;font-size:13px}.error-detail strong{color:#64748b}.error-detail span{color:#334155;line-height:1.55}.error-cause{color:#991b1b!important}.error-empty{padding:55px 20px;text-align:center;border:1px solid #bbf7d0;border-radius:16px;background:#f0fdf4;color:#166534}@media(max-width:650px){.error-tools,.error-card__head{align-items:flex-start;flex-direction:column}.error-detail{grid-template-columns:1fr;gap:3px}}</style>
<section class="error-center"><div class="error-tools"><form method="POST" action="{{ route('sistem.hatalari.yapayzeka') }}">@csrf<button type="submit" class="btn btn-primary"><i class="bi bi-cpu-fill"></i> Tara, Doğrula ve Raporla</button></form><div><strong>Yapay Zekâ ile Tara ve Raporla</strong><small class="d-block">Yalnız maskelenmiş hata özetleri analiz için gönderilir. Kaynak kodda düzeldiği doğrulanan kayıtlar açık listeden kaldırılır.</small></div></div>
@if(session('ai_hata_analizi'))<article class="error-card" style="border-left-color:#2563eb"><div class="error-card__head"><div><span class="error-code" style="background:#dbeafe;color:#1d4ed8">YAPAY ZEKÂ ANALİZİ</span><h2>Öneri raporu</h2></div></div><div style="margin-top:15px;white-space:pre-line;color:#334155">{{ session('ai_hata_analizi') }}</div></article>@endif
@if(session('error'))<div class="alert alert-warning mt-3"><strong>Tarama sonucu:</strong> {{ session('error') }}</div>@endif
@if($hatalar->isEmpty())<div class="error-empty"><i class="bi bi-shield-check"></i><strong>İzlenecek güncel bir hata bulunmuyor.</strong><span>Sistem hata günlüğünde ERROR veya CRITICAL seviyesinde kayıt yok.</span></div>@else<div class="error-list">@foreach($hatalar as $hata)<article class="error-card"><div class="error-card__head"><div><span class="error-code">{{ $hata['kod'] }}</span><h2>{{ $hata['ekran'] }}</h2></div><time class="error-time">{{ $hata['zaman'] }}</time></div><div class="error-detail"><strong>İşlem</strong><span>{{ $hata['islem'] }}</span><strong>Hata sebebi</strong><span class="error-cause">{{ $hata['sebep'] }}</span></div></article>@endforeach</div>@endif</section>
@endsection
