@extends('layouts.app')

@section('title', 'Şube Detayı')

@section('content')
<style>
    .sube-detail{max-width:1180px;margin:0 auto}.sube-detail *{box-sizing:border-box}.sube-detail__head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:22px}.sube-detail__head h1{margin:0;color:#17233c;font-size:27px;font-weight:800}.sube-detail__head h1 i{color:#2563eb;margin-right:8px}.sube-detail__head p{margin:7px 0 0;color:#64748b;font-size:14px}.sube-detail__actions{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;width:100%;margin:0 0 20px}.sube-detail__button{min-height:43px;padding:10px 12px;border-radius:10px;display:flex;justify-content:center;align-items:center;gap:7px;text-decoration:none;font-size:13px;font-weight:800;white-space:nowrap}.sube-detail__button--back{background:#dbeafe;color:#1d4ed8}.sube-detail__button--neutral{background:#e2e8f0;color:#334155}.sube-detail__button--edit{background:#fef3c7;color:#92400e}.sube-detail__card{padding:25px;background:#fff;border:1px solid #e5eaf1;border-radius:19px;box-shadow:0 7px 22px rgba(15,23,42,.06)}.sube-detail__card h2{margin:0 0 21px;padding-bottom:16px;border-bottom:1px solid #edf1f5;color:#1e293b;font-size:19px}.sube-detail__card h2 i{color:#2563eb;margin-right:7px}.sube-detail__grid{margin:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.sube-detail__grid div{min-width:0;padding:15px 16px;border:1px solid #e1e8f0;border-radius:12px;background:#f8fafc}.sube-detail__grid dt{margin-bottom:5px;color:#718096;font-size:12px;font-weight:700}.sube-detail__grid dd{margin:0;color:#263449;font-size:15px;font-weight:750;line-height:1.45;overflow-wrap:anywhere}.sube-detail__full{grid-column:1/-1}.sube-detail__status{display:inline-flex;padding:4px 9px;border-radius:999px;font-size:12px;font-weight:800}.sube-detail__status--active{background:#dcfce7;color:#15803d}.sube-detail__status--passive{background:#fee2e2;color:#b91c1c}@media(max-width:760px){.sube-detail__head{flex-direction:column}.sube-detail__actions{grid-template-columns:repeat(2,minmax(0,1fr))}.sube-detail__grid{grid-template-columns:1fr}.sube-detail__full{grid-column:auto}}@media(max-width:430px){.sube-detail__actions{grid-template-columns:1fr}.sube-detail__card{padding:18px}}
</style>
<section class="sube-detail">
    <header class="sube-detail__head"><div><h1><i class="bi bi-shop"></i> {{ $sube->sube_adi }}</h1><p>{{ $firma->unvan }} firmasına bağlı şube kartı.</p></div></header>
    @if(session('success'))<div class="alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert-danger">{{ session('error') }}</div>@endif
    <nav class="sube-detail__actions"><a href="{{ route('sube.index', $firma) }}" class="sube-detail__button sube-detail__button--back"><i class="bi bi-arrow-left"></i> Şubelere Dön</a><a href="{{ route('firma.show', $firma) }}" class="sube-detail__button sube-detail__button--neutral"><i class="bi bi-building"></i> Firma Kartı</a><a href="{{ route('ayarlar.index') }}" class="sube-detail__button sube-detail__button--neutral"><i class="bi bi-gear"></i> Ayarlara Dön</a><a href="{{ route('sube.edit', [$firma, $sube]) }}" class="sube-detail__button sube-detail__button--edit"><i class="bi bi-pencil"></i> Düzenle</a></nav>
    <article class="sube-detail__card"><h2><i class="bi bi-info-circle"></i> Şube Bilgileri</h2><dl class="sube-detail__grid"><div><dt>Bağlı Firma</dt><dd>{{ $firma->unvan }}</dd></div><div><dt>Şube Adı</dt><dd>{{ $sube->sube_adi }}</dd></div><div><dt>Vergi No</dt><dd>{{ $sube->vergi_no ?: '-' }}</dd></div><div><dt>Telefon</dt><dd>{{ $sube->telefon ?: '-' }}</dd></div><div><dt>Personel Sayısı</dt><dd>{{ $sube->personeller_count }} kişi</dd></div><div><dt>Durum</dt><dd><span class="sube-detail__status {{ $sube->aktif ? 'sube-detail__status--active' : 'sube-detail__status--passive' }}">{{ $sube->aktif ? 'Aktif' : 'Pasif' }}</span></dd></div><div class="sube-detail__full"><dt>Adres</dt><dd>{{ $sube->adres ?: '-' }}</dd></div></dl></article>
</section>
@endsection
