@extends('layouts.app')

@section('title', 'Şube Yönetimi')

@section('content')
<style>
    .sube-list{max-width:1280px;margin:0 auto}.sube-list *{box-sizing:border-box}.sube-list__head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:24px}.sube-list__head h1{margin:0;color:#15213b;font-size:26px;font-weight:800}.sube-list__head h1 i{color:#2563eb;margin-right:7px}.sube-list__head p{margin:7px 0 0;color:#64748b}.sube-list__actions{display:flex;gap:10px;flex-wrap:wrap}.sube-list__button{min-height:42px;padding:10px 14px;display:inline-flex;align-items:center;justify-content:center;gap:7px;border-radius:10px;text-decoration:none;font-size:13px;font-weight:800}.sube-list__button--back{background:#e2e8f0;color:#334155}.sube-list__button--new{background:#2563eb;color:#fff}.sube-list__grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.sube-card{padding:20px;background:#fff;border:1px solid #e5eaf1;border-radius:18px;box-shadow:0 6px 20px rgba(15,23,42,.06);display:flex;flex-direction:column}.sube-card__title{margin-bottom:16px;padding-bottom:15px;border-bottom:1px solid #edf1f5;display:flex;align-items:center;gap:9px;font-size:18px;font-weight:800;color:#1e293b}.sube-card__title i{color:#2563eb}.sube-card dl{margin:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.sube-card dt{margin-bottom:4px;font-size:12px;font-weight:650;color:#718096}.sube-card dd{margin:0;color:#334155;font-size:14px;font-weight:800;overflow-wrap:anywhere}.sube-card__full{grid-column:1/-1}.sube-card__status{padding:3px 8px;border-radius:999px;font-size:12px}.sube-card__active{background:#dcfce7;color:#15803d}.sube-card__passive{background:#fee2e2;color:#b91c1c}.sube-card__actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:21px}.sube-card__actions a{min-height:40px;display:flex;align-items:center;justify-content:center;gap:6px;border-radius:9px;text-decoration:none;font-size:12px;font-weight:800}.sube-card__detail{background:#dbeafe;color:#1d4ed8}.sube-card__edit{background:#fef3c7;color:#92400e}.sube-list__empty{grid-column:1/-1;min-height:165px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;border:1px dashed #cbd5e1;border-radius:18px;color:#64748b}.sube-list__empty i{font-size:30px;color:#94a3b8}@media(max-width:1050px){.sube-list__grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){.sube-list__head{flex-direction:column}.sube-list__actions{width:100%}.sube-list__button{flex:1}.sube-list__grid{grid-template-columns:1fr}}
</style>
<section class="sube-list">
    <header class="sube-list__head"><div><h1><i class="bi bi-shop"></i> {{ $firma->unvan }} · Şubeler</h1><p>Firma şubelerini ve şube bilgilerini yönetin.</p></div><div class="sube-list__actions"><a href="{{ route('firma.show', $firma) }}" class="sube-list__button sube-list__button--back"><i class="bi bi-arrow-left"></i> Firma Kartı</a><a href="{{ route('ayarlar.index') }}" class="sube-list__button sube-list__button--back"><i class="bi bi-gear"></i> Ayarlara Dön</a><a href="{{ route('sube.create', $firma) }}" class="sube-list__button sube-list__button--new"><i class="bi bi-plus-lg"></i> Yeni Şube</a></div></header>
    @if(session('success'))<div class="alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert-danger">{{ session('error') }}</div>@endif
    <div class="sube-list__grid">@forelse($subeler as $sube)<article class="sube-card"><div class="sube-card__title"><i class="bi bi-shop"></i>{{ $sube->sube_adi }}</div><dl><div><dt>Vergi No</dt><dd>{{ $sube->vergi_no ?: '-' }}</dd></div><div><dt>Telefon</dt><dd>{{ $sube->telefon ?: '-' }}</dd></div><div><dt>Personel Sayısı</dt><dd>{{ $sube->personeller_count }}</dd></div><div><dt>Durum</dt><dd><span class="sube-card__status {{ $sube->aktif ? 'sube-card__active' : 'sube-card__passive' }}">{{ $sube->aktif ? 'Aktif' : 'Pasif' }}</span></dd></div><div class="sube-card__full"><dt>Adres</dt><dd>{{ $sube->adres ?: '-' }}</dd></div></dl><div class="sube-card__actions"><a href="{{ route('sube.show', [$firma, $sube]) }}" class="sube-card__detail"><i class="bi bi-eye"></i> Detay</a><a href="{{ route('sube.edit', [$firma, $sube]) }}" class="sube-card__edit"><i class="bi bi-pencil"></i> Düzenle</a></div></article>@empty<div class="sube-list__empty"><i class="bi bi-shop-window"></i><strong>Henüz şube kaydı yok.</strong><span>İlk şubeyi oluşturarak başlayabilirsiniz.</span></div>@endforelse</div>
</section>
@endsection
