<?php
namespace App\Http\Controllers;

use App\Models\Firma; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;

class OperasyonController extends Controller {
    private function firma(Request $r, array $roller): int {
        abort_unless(auth()->check() && (auth()->user()->tamSistemYetkisiVarMi() || auth()->user()->isAdmin() || in_array(auth()->user()->role, $roller, true)), 403);
        $id=auth()->user()->tamSistemYetkisiVarMi() ? ($r->integer('firma_id') ?: Firma::where('aktif',true)->value('id')) : auth()->user()->firmaPersoneli?->firma_id;
        abort_unless($id && Firma::whereKey($id)->where('aktif',true)->exists(),403); return $id;
    }
    private function veri(int $firmaId): array {
        return ['musteriler'=>DB::table('musteris')->where('firma_id',$firmaId)->orderBy('ad_soyad')->get(), 'araclar'=>DB::table('araclar')->where('firma_id',$firmaId)->orderBy('plaka')->get(), 'subeler'=>DB::table('subes')->where('firma_id',$firmaId)->where('aktif',true)->get(), 'firmalar'=>Firma::where('aktif',true)->orderBy('unvan')->get()];
    }
    public function randevular(Request $r){ $firmaId=$this->firma($r,['usta','ofis']); return view('operasyon.merkez',array_merge($this->veri($firmaId),['modul'=>'randevu','firmaId'=>$firmaId,'kayitlar'=>DB::table('randevular')->leftJoin('musteris','musteris.id','=','randevular.musteri_id')->leftJoin('araclar','araclar.id','=','randevular.arac_id')->where('randevular.firma_id',$firmaId)->select('randevular.*','musteris.ad_soyad','araclar.plaka')->latest('baslangic')->get()])); }
    public function randevuKaydet(Request $r){$firmaId=$this->firma($r,['usta','ofis']);$v=$r->validate(['musteri_id'=>'nullable','arac_id'=>'nullable','sube_id'=>'nullable','hizmet_turu'=>'required|max:100','baslangic'=>'required|date','durum'=>'required|in:planlandi,teyitli,iptal,tamamlandi','notlar'=>'nullable|max:2000']);DB::table('randevular')->insert(array_merge($v,['firma_id'=>$firmaId,'usta_id'=>auth()->user()->isUsta()?auth()->id():null,'created_at'=>now(),'updated_at'=>now()]));return back()->with('success','Randevu ajandaya eklendi.');}
    public function sigorta(Request $r){$firmaId=$this->firma($r,['muhasebe']); return view('operasyon.merkez',array_merge($this->veri($firmaId),['modul'=>'sigorta','firmaId'=>$firmaId,'sigortalar'=>DB::table('sigorta_firmalari')->where('firma_id',$firmaId)->get(),'kayitlar'=>DB::table('sigorta_hasarlari')->leftJoin('sigorta_firmalari','sigorta_firmalari.id','=','sigorta_hasarlari.sigorta_firmasi_id')->leftJoin('araclar','araclar.id','=','sigorta_hasarlari.arac_id')->where('sigorta_hasarlari.firma_id',$firmaId)->select('sigorta_hasarlari.*','sigorta_firmalari.unvan as sigorta_unvan','araclar.plaka')->latest()->get()]));}
    public function sigortaKaydet(Request $r){$firmaId=$this->firma($r,['muhasebe']);$v=$r->validate(['dosya_no'=>'required|max:80','arac_id'=>'nullable','musteri_id'=>'nullable','sigorta_firmasi_id'=>'nullable','durum'=>'required|in:acik,ekspertiz,onaylandi,odendi,kapandi','onayli_tutar'=>'nullable|numeric|min:0','aciklama'=>'nullable|max:2000']);DB::table('sigorta_hasarlari')->insert(array_merge($v,['firma_id'=>$firmaId,'onayli_tutar'=>$v['onayli_tutar']??0,'tahsil_edilen'=>0,'created_at'=>now(),'updated_at'=>now()]));return back()->with('success','Hasar dosyası oluşturuldu.');}
    public function b2b(Request $r){$firmaId=$this->firma($r,['yedek_parca']);return view('operasyon.merkez',array_merge($this->veri($firmaId),['modul'=>'b2b','firmaId'=>$firmaId,'parcalar'=>DB::table('stok_parcalar')->where('firma_id',$firmaId)->where('aktif',true)->get(),'kayitlar'=>DB::table('b2b_siparisler')->where('firma_id',$firmaId)->latest()->get()]));}
    public function b2bKaydet(Request $r){$firmaId=$this->firma($r,['yedek_parca']);$v=$r->validate(['alici_unvan'=>'required|max:255','stok_parca_id'=>'nullable','urun_adi'=>'required|max:255','miktar'=>'required|numeric|gt:0','birim_fiyat'=>'required|numeric|min:0','durum'=>'required|in:taslak,onaylandi,hazirlaniyor,kargoda,tamamlandi,iptal']);DB::transaction(function()use($v,$firmaId){$tutar=$v['miktar']*$v['birim_fiyat'];$id=DB::table('b2b_siparisler')->insertGetId(['firma_id'=>$firmaId,'siparis_no'=>'B2B-'.now()->format('YmdHis'),'alici_unvan'=>$v['alici_unvan'],'durum'=>$v['durum'],'toplam_tutar'=>$tutar,'created_at'=>now(),'updated_at'=>now()]);DB::table('b2b_siparis_satirlari')->insert(['b2b_siparis_id'=>$id,'stok_parca_id'=>$v['stok_parca_id']??null,'urun_adi'=>$v['urun_adi'],'miktar'=>$v['miktar'],'birim_fiyat'=>$v['birim_fiyat'],'created_at'=>now(),'updated_at'=>now()]);});return back()->with('success','B2B sipariş kaydedildi.');}
}
